[team-32][BE][선을로&헤이호] 3번째 PR 요청
codesquad-members-2022/sidedish pull request #113
Opened 2022-04-25 02:31 UTC by dongkyu-park

안녕하세요. BE 32팀 선을로, 헤이호 입니다.

지난 번 PR에서 리뷰 해주신 내용을 살펴보며 코드를 수정 해보았습니다.
의도하셨던 바와 다르게 해석하여 진행한 부분이나, 추가로 부족한 부분들을 지적 해주시면 감사 하겠습니다.
매 번 꼼꼼하게 리뷰 남겨주셔서 감사합니다.👍

2022-04-25 03:30 UTC, dongkyu-park commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	public ResponseEntity<CommonResponse> loadListByType(
코드스멜에 대해 리뷰 해주셨던 내용이 `객체 안에 객체 안에 객체` 의 형태로 만들고, 제네릭 타입까지 사용 해버리니 가독성이 떨어진다? 는 의미로 해석하고 개선을 생각해 본 방법은 3가지 였습니다.

1. `ResponseEntity`에 담아 반환하는 형태를 없애고, 구현한 `CommonResponse` 안에 `ResponseEntity`가 하던 역할을 추가로 넣어 `CommonResponse` 객체 자체를 반환하기
```java
public CommonResponse<List<SimpleProductInfo>> loadListByType() ...
```
> `ResponseEntity` 는 응답 구조를 편리하게 만들기 위해 사용하는 것 인데, Controller의 코드 가독성을 위해 응답 Body 안에 들어갈 값을 정해주기 위한 목적으로 만들었던 `CommonResponse`를 `ResponseEntity` 역할을 하는 클래스로 변경하는 것은 주객전도 되는 느낌과, 불필요한 작업이 늘어나는 것이라 생각하여 1번은 제외 하였습니다.

2. 단순히 구체적인 반환 타입을 명시해주지 않고 반환하기
```java
public ResponseEntity loadListByType() ...
```
> 2번은 리뷰 해주신 내용의 근본적인 해결방법이 아니라 생각되어 제외 하였고,

3. `CommonResponse` 클래스의 제네릭 사용 없애기
```java
public class CommonResponse extends BasicResponse {

	private Object data;
```
> 3번 방법으로 코드를 변경해 보았습니다. `CommonResponse의 data`는 HttpMessageConverter에 의해 json 형태로 바뀌어 전송될 것이고, Object 형태로 사용하더라도, 개발자가 형변환에 신경 써야하는 부분은 없을거라 생각 했습니다.

2022-04-25 03:41 UTC, dongkyu-park commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
>  	}
```java
private CommonResponse createResponse() {
		return new CommonResponse(CommonCode.SUCCESS);
	}
```
위와 같은 형태로 매개변수로 `CommonCode`를 받지 않는 `성공` 표준 응답 객체를 만들려다, 

사용빈도는 적을 것 같지만 `204` 와 같은 상태코드를 리턴하는 경우엔 해당 메서드를 재사용 하지 못할 것 같다 생각하여 PR을 보낸 형태와 같이 만들었습니다. 

각각의 메서드명으로 매개변수가 다른 2개의 생성자가 의미하는 바를 조금 더 한 눈에 파악할 수 있지 않을까 생각 했습니다.

2022-04-25 03:44 UTC, dongkyu-park commented
```java
public static Product updateQuantity(Product product, Integer quantity) {
		return new Product(product.getId(), product.getName(), product.getContent(),
			product.getPrice(), quantity,
			product.getDishType(), product.getSideDishType(), product.getApplyEvent(),
			product.getImgUrl());
	}
```

> `nit`
quantity 하나를 바꾸기 위해 이 많은 필드를 새로 만들어야 할까요.
불변성을 우선하는 관점에서 나쁜 방법은 아니지만, 다른 방법에 대해서도 고민해보시면 좋을 것 같습니다.

빌더 패턴 같은 것을 말씀 해주신걸까? 생각 했었는데, 다른 방법들이 무엇이 있는지 잘 모르겠어서 질문을 드리고 싶습니다. 다른 방법들에 대한 키워드를 부탁 드려도 될까요?

2022-04-25 04:36 UTC, Hyune-c requested changes
수고하셨습니다. 

1. ProductRepository는 인터페이스이고, MemoryProductRepository는 구현체인데 suffix가 같아서 헷갈립니다.
2. Discount enum을 좀 더 강화할 수 있을 것이지만 지금도 나쁘지는 않습니다. 
3. 슬슬 실DB를 붙여보시면 좋을 것 같습니다.

2022-04-25 04:36 UTC, Hyune-c commented on be/src/main/resources/sql/schema.sql
> +    side_dish_type    VARCHAR(30),
`nit`
sidedish도 dish처럼 하나의 명사로 볼 수 있을 것 같아요.

2022-04-25 04:36 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/service/ProductService.java
> +		return productRepository.findById(id).get().createDTO();
null에 대한 예외를 처리하지 않는다면 optional을 사용할 의미도 없는 것 아닐까요?

2022-04-25 04:36 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +	}
entity가 dto를 알게된다면, dto가 늘어날떄마다 entity에 변화가 생길 것 같습니다.

2022-04-25 04:36 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +
`nit`
무의미한 개행은 조절해주세요.

2022-04-25 04:36 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Discount.java
> +	public static Discount setSaleType(String applyEvent) {
set은 이미 존재하는 객체의 필드를 변경할 때 사용되는 prefix입니다.
지금의 메서드는 흐름상 새로운 객체를 반환합니다.

2022-04-25 04:36 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Discount.java
> +public enum Discount {
`nit`
enum은 관습적으로 type과 같은 suffix를 활용합니다.

2022-04-25 04:36 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Discount.java
> +		throw new AssertionError("올바르지 않은 할인 정보가 들어 왔습니다.");
`nit`
이왕 switch문을 활용하신다면 default도 활용해보시는 건 어떨까요.

2022-04-25 04:36 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	public ResponseEntity<CommonResponse> loadListByType(
표준 응답 객체, 표준 에러 객체는 고려해야될 내용이 상당히 많습니다.
그리고 회사마다 이것을 구현하는 내용도 미묘하게 다르기에 지금 정도만 공부하셔도 좋을 것 같습니다.

좀 더 참고할만한 내용을 남깁니다.

https://daddyprogrammer.org/post/404/spring-boot2-design-api-interface-and-data-structure/

2022-04-25 04:36 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
>  	}
상태코드를 다양하게 사용하시려면 매개변수로 받는 것이 좋을 수도 있습니다.

`nit`
하지만 상태코드를 소수만 사용한다면 그것에 맞는 생성자를 만들 수도 있습니다. 
ex) `OKCommonResponse()` `NoContentCommonResponse`

2022-04-25 04:36 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +		return (int) (price * discount.getValue());
double을 int로 캐스팅하면 소수점은 절삭될 것인데 의도한 것인가요?

2022-04-25 04:38 UTC, Hyune-c commented
> 빌더 패턴 같은 것을 말씀 해주신걸까? 생각 했었는데, 다른 방법들이 무엇이 있는지 잘 모르겠어서 질문을 드리고 싶습니다. 다른 방법들에 대한 키워드를 부탁 드려도 될까요?

- jpa에서 어떻게 수정하고 있는지 공부해보시면 좋을 것 같습니다. (더티 체킹)
- 제일 쉬운건 setter 입니다.

2022-04-25 08:36 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	public ResponseEntity<CommonResponse> loadListByType(
https://techblog.woowahan.com/7828/

오늘 우형 블로그에 올라온 글 중에 연결해서 생각해보시면 좋은 부분이 있네요.
하지만 앞에 말한 것 처럼 이 부분은 고려해야될 부분이 상당히 많기에 지금 너무 잘 고치려고 노력하지는 마세요.

![image](https://user-images.githubusercontent.com/55722186/165051846-42504acc-fb1d-4155-b547-9c509c2ffbcd.png)

2022-04-25 09:31 UTC, dongkyu-park commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	public ResponseEntity<CommonResponse> loadListByType(
와... Dan!! 너무너무 감사합니다

2022-04-26 01:56 UTC, Hyune-c commented on be/src/main/resources/sql/schema.sql
> +    price             INT               NOT NULL,
이 필드만 INT인 이유가 있을까요?
다른 선언과 일관성이 떨어집니다.

2022-04-26 01:56 UTC, Hyune-c commented on be/src/main/resources/sql/schema.sql
> +    id                INTEGER           PRIMARY KEY   AUTO_INCREMENT,
pk는 integer와 long 중 어떤 것이 좋을까요?

2022-04-27 06:37 UTC, merged

2022-04-27 07:41 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/service/ProductService.java
> +		return productRepository.findById(id).get().createDTO();
`orElseThrow()`로 예외 처리를 하였습니다!

2022-04-27 08:05 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +	}
domain 객체가 dto 객체를 모르도록,
dto 가 스스로 domain을 받아서 생성하도록 수정하였습니다.
정적 팩토리 메소드 방식을 사용하였습니다.

2022-04-27 08:10 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/domain/Discount.java
> +	public static Discount setSaleType(String applyEvent) {
`convertSaleType()`로 변경 하였습니다!

2022-04-27 08:19 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +		return (int) (price * discount.getValue());
아뇨 의도하지 않았습니다. 잘 몰랐네요;
`Math.round()`라는 메소드를 사용해서 곱해진 double 값을 반올림 한 이후에 int로 캐스팅 하게 변경하였습니다.

2022-04-27 08:30 UTC, fpzk5656 commented on be/src/main/resources/sql/schema.sql
> +    price             INT               NOT NULL,
아뇨 없습니다. 저번 리뷰 때 변경을 했는데 change request 때 반영이 안됬던 상황이라 그대로 갔나보네요

2022-04-27 08:48 UTC, fpzk5656 commented on be/src/main/resources/sql/schema.sql
> +    id                INTEGER           PRIMARY KEY   AUTO_INCREMENT,
구글링을 꽤나 해보았지만, 명확하게 뭐가 더 좋은지는 모르겠네요
Long 자체가 Integer의 두배이상 허용 가능하다는 장점 이외에 별다른 장점이 있는 지는 모르겠습니다.

2022-04-27 09:07 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/domain/Discount.java
> +		throw new AssertionError("올바르지 않은 할인 정보가 들어 왔습니다.");
넵 적용하였습니다!