[Team-35 BE] OAuth를 사용한 로그인 기능 및 반찬 상세정보, 주문하기 기능 구현
codesquad-members-2022/sidedish pull request #122
Opened 2022-04-27 06:47 UTC by naneun

안녕하세요 Team-35 에서 백엔드를 담당한 테리와 리아코입니다. 🙆‍♀️🙆‍♂️
OAuth를 사용한 로그인 기능 및 반찬 상세정보, 주문하기 기능을 구현하여 pr 요청드립니다 😄

# API 명세
  - http://54.180.92.20:8080/swagger-ui/index.html
  - GET /api/exhibitions/{exhibitionId} 특정 기획전 카테고리 목록 조회
```
{
  "exhibitionId": 1,
  "exhibitionTitle": "일반 진열 상품",
  "categoryResponses": [
    {
      "categoryId": 1,
      "categoryTitle": "든든한 메인요리"
    },
    {
      "categoryId": 2,
      "categoryTitle": "뜨끈한 국물요리"
    },
    {
      "categoryId": 3,
      "categoryTitle": "정갈한 밑반찬"
    }
  ]
}
```
  - POST /api/order-sheets 주문하기<br>
  ![SmartSelectImage_2022-04-27-15-42-43](https://user-images.githubusercontent.com/47964708/165457368-ce851672-b694-419c-85c3-20173f674eab.png)  
```
{
  "id": 1,
  "quantity": 5,
  "totalAmount": 5000,
  "createdAt": [
    2022,
    4,
    27,
    15,
    36,
    5,
    778772900
  ]
}
```
  - GET /api/sidedishes/{sideDishId} 반찬 상세 정보 조회
```
{
  "sideDishId": 1,
  "imageUrls": [
    "https://naneun-220320.s3.ap-northeast-2.amazonaws.com/terria/%EC%83%88%EC%BD%A4%EB%8B%AC%EC%BD%A4_%EC%98%A4%EC%A7%95%EC%96%B4%EB%AC%B4%EC%B9%A8_1.png"
  ],
  "name": "새콤달콤 오징어무침",
  "description": "국내산 오징어를 새콤달콤하게",
  "disCountPrice": 6750,
  "price": 7500,
  "stock": 3,
  "shippingInfo": "서울 경기 새벽 배송, 전국 택배 배송",
  "shippingFee": 2500,
  "exemptionCondition": 40000,
  "discountEventResponses": [
    {
      "discountEventId": 2,
      "title": "런칭특가"
    }
  ]
}
```
  - GET /api/sidedishes/category/{categoryId} 특정 카테고리에 속한 반찬 목록 조회(페이징 처리)
```
{
  "totalCount": 5,
  "sideDishCardResponses": [
    {
      "sideDishId": 9,
      "imageUrl": "https://naneun-220320.s3.ap-northeast-2.amazonaws.com/terria/%EC%98%A4%EB%A6%AC_%EC%A3%BC%EB%AC%BC%EB%9F%AD_%EB%B0%98%EC%A1%B0%EB%A6%AC_1.png",
      "name": "오리 주물럭_반조리",
      "description": "감칠맛 나는 매콤한 양념",
      "disCountPrice": 12640,
      "price": 15800,
      "shippingInfo": "서울 경기 새벽 배송, 전국 택배 배송",
      "discountEventResponses": [
        {
          "discountEventId": 1,
          "title": "이벤트특가"
        },
        {
          "discountEventId": 2,
          "title": "런칭특가"
        }
      ]
    },
    {
      "sideDishId": 10,
      "imageUrl": "https://naneun-220320.s3.ap-northeast-2.amazonaws.com/terria/%EC%9E%A1%EC%B1%84_1.png",
      "name": "잡채",
      "description": "탱글한 면과 맛깔진 고명이 가득",
      "disCountPrice": 11610,
      "price": 12900,
      "shippingInfo": "서울 경기 새벽 배송, 전국 택배 배송",
      "discountEventResponses": [
        {
          "discountEventId": 1,
          "title": "이벤트특가"
        }
      ]
    },
    {
      "sideDishId": 11,
      "imageUrl": "https://naneun-220320.s3.ap-northeast-2.amazonaws.com/terria/%EC%86%8C%EA%B0%88%EB%B9%84%EC%B0%9C_1.png",
      "name": "소갈비찜",
      "description": "촉촉하게 밴 양념이 일품",
      "disCountPrice": 26010,
      "price": 28900,
      "shippingInfo": "서울 경기 새벽 배송, 전국 택배 배송",
      "discountEventResponses": [
        {
          "discountEventId": 1,
          "title": "이벤트특가"
        }
      ]
    },
    {
      "sideDishId": 12,
      "imageUrl": "https://naneun-220320.s3.ap-northeast-2.amazonaws.com/terria/%EA%B0%84%EC%9E%A5_%EC%BD%94%EB%8B%A4%EB%A6%AC%EC%A1%B0%EB%A6%BC_1.png",
      "name": "간장 코다리조림",
      "description": "쫀득한 코다리를 국내산 간장소스로 맛있게 조렸어요",
      "disCountPrice": 14900,
      "price": 14900,
      "shippingInfo": "서울 경기 새벽 배송, 전국 택배 배송",
      "discountEventResponses": []
    }
  ]
}
```

# 한 일
  - [x] OAuth를 사용한 로그인 기능 구현
  - [x] 반찬 상세정보, 주문하기 기능 구현

# 해야할 일
  - [ ] ngnix 를 사용한 배포

감사합니다! .🤗

2022-04-27 13:33 UTC, tmdgusya requested changes
고생하셨습니다. 몇가지만 수정하시고 다음 미션으로 넘어가시죠.

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/api/OrderSheetController.java
> +    public OrderSheetResponse makeOrderSheet(@ModelAttribute @Valid OrderSheetRequest orderSheetRequest) {
Validation 하는 습관 좋습니다. 👍

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/AccessToken.java
> +    }
OAuth 도입이라.. 삽질이 많았겠지만 어찌어찌 잘 하셨나보네요 ㅎㅎ 축하드립니다 🥇

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/OrderSheet.java
> +    public static OrderSheet of(int quantity, int totalAmount, long sideDishId, long memberId) {
파라미터가 많을때는 보통 `of` 를 쓰고, 적을때는 `from` 을 쓰죠 ㅎㅎ 👍 
좋습니다. 혹시 보통 컨벤션을 잘 모르실까봐 말씀드려봤어요.

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/dto/response/sidedish/SideDishDetailResponse.java
> +    @ApiModelProperty(required = true, value = "반찬 아이디")
프론트분들이 일하기 좋으시겠네요 ㅎㅎ 👍

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/dto/response/sidedish/SideDishDetailResponse.java
> +                (int) (sideDish.getPrice() * (1.0 - totalDiscountRate)) / 10 * 10,
계산 로직은 따로 추출해주세요. 자칫 관리가 안될 가능성이 높아보입니다.

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/error/HandlerAdvice.java
> +    }
예외 종류에 따라 차이가 없다면 나눌 이유가 굳이 있나 싶기도 해요.
차라리 같은 부모를 상속시키면 코드를 줄일 수 있지 않을까요?

```java
OAuthException extends Team35DefaultException

ExhibitionException extends Team35DefaultException

 @ExceptionHandler(Team35DefaultException.class)
```

대략적으로 위와 같이 풀어볼수 있을거 같은데.

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/error/exception/OAuthException.java
> +public class OAuthException extends RuntimeException {
위의 조언이 여기서 RuntimeException 을 상속하는게 아니라 Team35DefaultException 을 하나 만들고 

```java
public class Team35DefaultException extends RuntimeException 

public class OAuthException extends Team35DefaultException
```

요 방향을 말한거였습니다.

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/service/GitHubAuthService.java
> +    }
요건 개인적인 의견인데 저 같은 경우에는 외부로 API 를 연동해야 하는 부분은 GithubAdapter 와 같은 클래스로 분리해서 public method 로 열어두는 편이에요. 왜냐면 다른 곳에서 쓰일 수도 있고, 하나의 end-point 로 호출하는 API 들을 한눈에 관리할 수도 있어서요. 지금 하신 방법이 틀렸다는 건 아니고, 이런 방법도 있다는 거에요 ㅎㅎ 한번 고려해보셔도 좋을거 같아요.

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/service/GitHubAuthService.java
> +    }
분리하면 `"application/vnd.github.v3+json"` 요런것도 상수로 관리하기 좀 더 쉬울거에요.

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/service/OrderSheetService.java
> +        int remainStock = sideDish.getStock();
null 일 경우 NullPointerException 아닌가요? orElseThrow 를 이용하시죠.

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/service/SideDishService.java
> +        for (SideDish sideDish : sideDishRepository.findByCategoryId(categoryId, page * ITEM_COUNT, ITEM_COUNT)) {
`sideDishRepository.findByCategoryId(categoryId, page * ITEM_COUNT, ITEM_COUNT)` 요 부분은 for 문에 적지말고 분리해주세요. 헷갈릴 여지가 너무 높아보여요.

2022-04-27 13:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/service/GitHubAuthService.java
> +        log.info("Member: {}", memberRepository.findByUserIdAndProvider(userId, provider)
**memberRepository.findByUserIdAndProvider(userId, provider)** 는 따로 분리하고 그 변수를 log 에서 찍어주세요 ㅎㅎ
log 에서 메소드를 호출하는건 좋지 않아보여요

2022-04-27 14:42 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/OrderSheet.java
> +    public static OrderSheet of(int quantity, int totalAmount, long sideDishId, long memberId) {
ㅎㅎ 사실.. 몰랐습니다! 알려주셔서 감사합니다 로치~ 🤩

2022-04-27 14:42 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/dto/response/sidedish/SideDishDetailResponse.java
> +    @ApiModelProperty(required = true, value = "반찬 아이디")
다 로치께서 조언해주신 덕분입니다! ㅎㅎ 😄 감사합니닷!

2022-04-27 14:43 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/dto/response/sidedish/SideDishDetailResponse.java
> +                (int) (sideDish.getPrice() * (1.0 - totalDiscountRate)) / 10 * 10,
넵! 분리하도록 하겠습니다! 🙋‍♂️

2022-04-27 14:44 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/error/HandlerAdvice.java
> +    }
차이가 생길 줄 알았는데 없었습니다! ㅎㅎ.. 조언해주신 대로 바로 수정토록하겠습니다~

2022-04-27 14:45 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/error/exception/OAuthException.java
> +public class OAuthException extends RuntimeException {
넵! 더 상세히 말씀주셔서 감사드립니다~ ㅎㅎ 🤩

2022-04-27 14:46 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/service/GitHubAuthService.java
> +        log.info("Member: {}", memberRepository.findByUserIdAndProvider(userId, provider)
넵! 조언 감사드립니다 로치! 바로 수정하겠습니닷! 😃

2022-04-27 14:48 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/service/GitHubAuthService.java
> +    }
도전해보겠습니다! 감사합니다 로치~! 🤗

2022-04-27 14:49 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/api/OrderSheetController.java
> +    public OrderSheetResponse makeOrderSheet(@ModelAttribute @Valid OrderSheetRequest orderSheetRequest) {
로치께서 리뷰 달아주신 덕분에 Validation 에 대해 많은 것을 알아볼 수 있었습니다 ㅎㅎ

2022-04-27 14:50 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/AccessToken.java
> +    }
학습이 덜 된 상태라 어설픈 곳이 많은데 😅 더 공부해보도록 하겠습니다! ㅎㅎ 감사합니다 로치~ 🤩

2022-04-27 14:55 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/service/SideDishService.java
> +        for (SideDish sideDish : sideDishRepository.findByCategoryId(categoryId, page * ITEM_COUNT, ITEM_COUNT)) {
넵! 바아로 반영하도록 하겠습니닷! 🙋‍♂️

2022-04-27 17:14 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/service/GitHubAuthService.java
> +    }
오오오!! 훨씬 깔끔하고 말씀해주신대로 관리도 용이해졌습니다! ㅎㅎ 🤩🤩 많이 알려주셔서 많이많이 감사드립니다 로치~!

2022-04-28 02:07 UTC, mybloom commented on backend/src/main/java/com/terria/sidedish/error/exception/OAuthException.java
> +public class OAuthException extends RuntimeException {
로치~ Exception관리에 대해서 상세하게 리뷰해주셔서 감사합니다.

2022-04-28 02:08 UTC, mybloom commented on backend/src/main/java/com/terria/sidedish/service/OrderSheetService.java
> +        int remainStock = sideDish.getStock();
수정해서 반영하도록 하겠습니다. Optional을 어떻게 사용해야할지 감이 잡히지 않았는데 상세히 말씀해주셔서 코드 짤때 많은 도움이 되었습니다!

2022-04-28 02:26 UTC, mybloom commented on backend/src/main/java/com/terria/sidedish/api/OrderSheetController.java
> +    public OrderSheetResponse makeOrderSheet(@ModelAttribute @Valid OrderSheetRequest orderSheetRequest) {
습관 형성할 수 있도록 리뷰 남겨주셔서 개발할 때 해당 부분 신경쓰면서 할 수 있도록 해주셔서 감사합니다~

2022-04-28 07:16 UTC, naneun commented
리뷰 주신 내용들을 반영했습니다! ㅎㅎ 리뷰 감사드립니다 로치! 🤩

2022-04-28 12:08 UTC, merged

2022-04-28 12:08 UTC, tmdgusya commented
넵 고생하셨습니다 :)