[Team34][BE] sidedish 배포와 주요 기능 일부 구현
codesquad-members-2022/sidedish pull request #130
Opened 2022-04-27 07:22 UTC by nak253

안녕하세요 @tmdgusya 34조의 백엔드 개발을 맡은 Dave와 Hoo입니다 :)
진행 사항이 더디지만 리뷰해주시는 내용을 참고하여 열심히 하겠습니다. 감사합니다!

## 작업 내용
- 스프링 부트 프로젝트 수동 배포
    - [서버 URL](http://3.37.71.175:8080/)
    - [API 명세](http://3.37.71.175:8080/swagger-ui/index.html)
- 카테고리 도메인 기능 구현
- 반찬 도메인 기능 구현

## 앞으로 할 일
- 프론트 배포
- 자동 배포
- 주문 도메인 기능 구현

## 질문 사항
1. 도메인 객체 -> DTO 변환 시, 변환 로직을 DTO에서 가질지, 도메인 객체에서 가질지에 대한 고민이 있습니다.
2. 할인가 계산과 같은 비지니스 로직을 도메인 객체에서 가지는 것이 맞을지, 서비스 레이어에서 가지고 있는 것이 맞을지 고민이 됩니다.

**질문에 대한 자세한 사항은 관련 코드에 코멘트를 남겨 놓겠습니다!**
<br>
<br>

2022-04-27 07:35 UTC, nak253 commented on BE/src/main/java/com/team34/sidedish/domain/Category.java
> +    }
1. 도메인 객체 -> DTO 변환 시, 변환 로직을 DTO에서 가질지, 도메인 객체에서 가질지에 대한 고민이 있습니다.

- 도메인 객체가 DTO 변환을 담당하는 경우
   - 변경이 잦은 DTO객체에 의존성이 생겨, DTO 내부가 바뀔 때마다 도메인 객체도 수정해야 한다는 단점이 있습니다.
- DTO에서 도메인 객체를 매개변수로 갖는 생성자를 통해 DTO를 생성하는 경우
    ```java
    CategoryResponse (Category category) {
      this.id = category.getId();
       ....
     }
   ```
    - DTO가 도메인 객체에 대한 내부 구현 사항을 알고 있게 된다는 단점이 있습니다. (getter 사용)

저희는 위의 두 가지 방법중에서 DTO가 도메인 객체의 내부 구현 사항을 알게 된다는 단점이 더 크게 느껴져, 도메인 객체가 DTO 변환을 담당하도록 코드를 작성하였습니다.
이에 대한 리뷰어님의 의견은 어떠신가요?

2022-04-27 07:38 UTC, nak253 commented on BE/src/main/java/com/team34/sidedish/domain/Dish.java
> +    }
2. 할인가 계산과 같은 비지니스 로직을 도메인 객체에서 가지는 것이 맞을지, 서비스 레이어에서 가지고 있는 것이 맞을지 고민이 됩니다.

2022-04-27 13:10 UTC, tmdgusya requested changes
고생하셨습니다.
개인적으로 Domain 에서 DTO 로 변환하는건 전 좀 별로라고 생각해요.
Domain 은 Domain 외에 아무것도 몰라야 한다고 생각합니다.

그쪽만 바꾸시고 다음 미션 진행하시죠.

2022-04-27 13:10 UTC, tmdgusya commented on BE/src/main/java/com/team34/sidedish/domain/Category.java
> +    private List<Category> children = new ArrayList<>();
재할당하는 일이 없다면 final 을 써보는건 어떨까요

2022-04-27 13:10 UTC, tmdgusya commented on BE/src/main/java/com/team34/sidedish/domain/Category.java
> +    }
도메인 객체가 DTO 에 관한 로직을 가지는게 맞을까요? DTO 가 100 개 있다고 해도 위와 같이 할 수 있을까요?

일단 고민 하신 이유도 알거 같습니다. 좋은 고민이라고 생각해요.
다만 DTO 가 바뀔때마다 Domain 이 바뀌어야 하는게 정상적인가요..? 전 그부분은 이해가 잘 가지 않아요.

2022-04-27 13:10 UTC, tmdgusya commented on BE/src/main/java/com/team34/sidedish/domain/Category.java
> +    }
Domain 생성자에 맞게 DTO 가 알아서 변환되어야 하는건 아닐까요?

2022-04-27 13:10 UTC, tmdgusya commented on BE/src/main/java/com/team34/sidedish/domain/Dish.java
> +    @MappedCollection(idColumn = "dish_id", keyColumn = "id")
👍

2022-04-27 13:10 UTC, tmdgusya commented on BE/src/main/java/com/team34/sidedish/domain/Dish.java
> +    }
이건 Response 로 이동해주세요

2022-04-27 13:10 UTC, tmdgusya commented on BE/src/main/java/com/team34/sidedish/domain/Dish.java
> +    }
좋은 고민이네요.
제 생각엔 요건 좀 애매한것 같기도  해요. 
뭔가 할인가를 계산하는 도메인 Layer 가 있어야 하는게 아닌지..(쉽게 이야기하면 Service 계층)
나중에 할인 정책이나 여러가지 조건들이 추가된다고 했을때, 무언가 Domain 객체에 계속해서 의존성이 높아질것만 같아요.
근데 사실 지금 하신것처럼 도메인에 두고 후에 정책들이 추가된다면 옮겨도 괜찮을거 같다? 라는 생각도 드네요. 요 부분은 한번 제 의견과 비교해보시고 더 괜찮은 방향이 어딜지 고민하시고 결정하시면 될것 같아요.

2022-04-27 13:10 UTC, tmdgusya commented on BE/src/main/java/com/team34/sidedish/domain/Category.java
> +    }
저는 오히려 DTO 의 경우 어떻게 보면 Front 혹은 App 의 Web 에 내려줘야 할 정보인데, 그걸 Domain 에서 알아야 한다는게 더 이상하게 느껴져요.

2022-04-27 13:10 UTC, tmdgusya commented on BE/src/test/java/com/team34/sidedish/repository/CategoryRepositoryTest.java
> +class CategoryRepositoryTest {
Service 단에 대한 Test 가 부족해보여요.
단순히 DB 에서 가져와서 뿌려준다고 생각해도. verify 등 흐름에 관한 테스트는 해야되지 않나 싶어요.
예를 들면 어떤 상황일때 어떤 메소드는 반드시 호출되거나, 호출되지 않는다. 이런것들이요.

verify 로 검색하시면 나올거에요.

2022-04-27 13:10 UTC, tmdgusya commented on BE/src/main/java/com/team34/sidedish/domain/Badge.java
> +    }
👍

2022-04-28 07:43 UTC, nak253 commented on BE/src/main/java/com/team34/sidedish/domain/Category.java
> +    }
리뷰해주신 부분을 참고하여 DTO에서 도메인 객체를 매개변수로 갖는 생성자를 통해 DTO를 생성하도록 코드를 변경하였습니다!! 부족한 점이 있다면 언제든 말씀해주세요.

2022-04-28 08:22 UTC, nak253 commented on BE/src/main/java/com/team34/sidedish/domain/Dish.java
> +    }
말씀해주신 사항을 코드에 반영하다가 두가지 질문이 생겼습니다.

1. 일단 Dish 도메인에 있었던 할인가 계산을 Enum Badge에 옮겨보았습니다.
이 변경에 대한 리뷰어님의 생각은 어떠신가요?
전처럼 도메인에 할인가 계산로직이 있는것이 나은지, 변경사항이 더 나은지 판단이 잘 되지 않습니다.

2. 일단 말씀해주신대로 Service 계층으로 옮긴다면 다음과 같이 DishResponse 생성자에 service에서 계산한 할인가를 넘겨주거나, setter를 이용하여 DTO에 값을 지정해야 한다고 생각했습니다.
```java
//DishResponse 생성자에 service에서 계산한 할인가를 넘겨주는 경우
//DishResponse 클래스
public DishResponse(Dish dish , int discountPrice) {
	...
	this.discountPrice = discountPrice ;
	...
}
```

```java	
//setter를 이용하여 DTO에 값을 지정하는 경우
//DishServcie 클래스
	 DishResponse dishResponse = new DishResponse(dish);
	dishResponse.setDiscountPrice(calculateDiscountPrice());
```
하지만 위의 방식은 익숙치않아서 근거없는 어색함이 느껴집니다.
위의 코드 작성이 기존의 저희가 작성한 방식보다 자연스러운 방식인가요?

2022-04-28 08:39 UTC, nak253 commented on BE/src/main/java/com/team34/sidedish/domain/Category.java
> +    private List<Category> children = new ArrayList<>();
해당 사항 변경하였습니다 😀

2022-04-28 12:07 UTC, tmdgusya commented on BE/src/main/java/com/team34/sidedish/domain/Dish.java
> +    }
음 참 애매하네요. 이건 도메인 객체가 가지고 있는게 저도 이렇게 보니 맞아보이네요~! 일단 초기 코드대로 가시죠!

2022-04-28 12:07 UTC, tmdgusya commented
고생하셨습니다 :)

2022-04-28 12:07 UTC, merged