[Team-19 iOS Chez & Jason] SideDish - 메인화면 구현
codesquad-members-2022/sidedish pull request #139
Opened 2022-04-27 07:41 UTC by asqw887

### **🧑🏼‍💻 작업 목록**

- [x]  첫번째 PR comment 답변
- [x]  메인화면 구현 
- [x]  SwiftLint 학습 및 적용
- [x]  mock up json data ⇒ main / soup / side 분리해서 새로 만들기
- [x]  목업 데이터 파싱해서 셀에 데이터 넣기
- [x]  enum Error 타입으로 처리
- [x]  UIImage URL URLSession 비동기 처리

### **💭 학습 키워드**

- Error 처리
- @escaping closure
- swiftLint
- HTTP 통신허용
- UnitTest
- OS_Log

### **🤔고민과 해결**

- FoodManager가 [Food] 를 각각 가지고 있는게 최선의 방법일지 고민이 됩니다...

### **💬  실행 화면**

https://user-images.githubusercontent.com/59790540/165465082-2241f161-6573-4976-98e2-423d9bfef878.mp4

### **💬 부연 설명**

- 지난 피드백에서 에러 처리에 대한 코멘트가 있어 학습하고 enum 타입으로 처리를 하고 시스템 로그를 출력하는 방식으로 리팩토링 해보았습니다 :) 테스트로 Json파일의 statusCode를 500으로 바꾸고 실행 해보았습니다. 

![Screen Shot 2022-04-27 at 16 11 59 PM](https://user-images.githubusercontent.com/59790540/165466854-66cc7e2f-e131-43ec-bfe7-0a90a08ca8b3.png)

### **🙋🏻 질문 거리**
- 이미지를 요청하고 테이블 뷰 셀에 넣어주는 작업에서 몇몇 이미지가 나오지 않는 문제점이 있습니다.
  loadImage 함수에서 data가 안들어오거나 error가 발생할때 로그를 찍어서 확인을 해보았으나, 이미지 다운로드는 성공적으로 되지만 셀에 이미지가 들어갈때 문제점이 있다고 판단했습니다. ( 모델(Food)에서는 데이터가 정상적으로 들어와서 VC로 넘어가는 것 같습니다. 하지만 View에서 VC로 데이터가 출력되는 부분에서 문제가 있다고 판단됩니다! )
그리고 현재 테이블뷰를 스크롤되면서 데이터가 변형이되는 문제도 있는데, 이와 관련이 있지 않나 생각해보았습니다. 혹시 저희가 놓치고 있는 부분이 있다면 알려주시면 감사하겠습니다..

2022-04-27 07:49 UTC, JasonLee0223 commented on sideDish/sideDish/Model/FoodManager.swift
> +    }
Model(Food)를 FoodManager가 관리할 수 있게 작성을 하였습니다. 이후  FoodManager가 main,soup,side 를 각각의 객체를 가지고 관리하는게 좋은 답안인지 아니면 하나로 통합하여 관리하는게 맞는 방법일 지 고민이 됩니다...

2022-04-27 08:00 UTC, JasonLee0223 commented on sideDish/sideDish/JSON/JsonConvertor.swift
> +}
URLSession으로 API요청하여 데이터 받아왔을때는 CustomStringConvertible 프로토콜을 채택하지않고 처리하지않고 해보려고합니다!

2022-04-27 08:49 UTC, GangWoon requested changes
1. 이전 피알에서 그려주신 구조에 대해서 작성하신 코드와 동일한지, 구현했을때의 이득이 무엇인지 점검하면 좋은 시기인거 같습니다. 
해당 부분에 대해서 저한테 편하게 알려주셨으면 좋겠네요. 글로만 표현하기 어렵다면 다시 그림으로 표현하시거나, 말로 표현하셔도 괜찮습니다.

2. 에러가 나는 상황을 콘솔에서만 알수 있다면, 사용자는 현재 앱의 상태가 문제가 발생했는지 명확하게 알 수 있을까요?? 문제가 발생한 상황에서 사용자에게 전달하려면 어떤 과정이 필요할까요? (너무 에러에 대해서 고민하실 필요는 없습니다.)

3. 컬랙션뷰에서 해당 셀을 꾸밀때 일반 뷰와 동일하게 꾸밀까요?? addsubview를 통해서 접근했나요? 일반적인 뷰와 다른점이 존재할 거 같은데 어떤 부분들이 다를까요??

4. Main, ... 세가지 항목을 따로 관리하다보니 데이터를 사용해서 꾸밀때 조금 어색하게 느껴지는 코드들이 존재합니다. 어떤식으로 접근하면 의도에 대해서 명확하게 표현할 수 있을까요? (저는 이런거 생각하는게 제일 재밋더라구요 ㅋㅋ)

2022-04-27 08:49 UTC, GangWoon commented on sideDish/sideDish/Extension/UIImageView+Extension.swift
> +    }
네트워크 통신은 누가 담당하는게 좋을까요?
이전 PR 그린 그림을 보며, 다시 한번 생각해보셨으면 좋겠습니다.

2022-04-27 08:49 UTC, GangWoon commented on sideDish/sideDish/Model/Food.swift
> +    private(set) var image: URL
이름만 확인했을때는 UIImage 타입일거 같다는 생각이 드는거 같습니다.

2022-04-27 08:49 UTC, GangWoon commented on sideDish/sideDish/Model/FoodManager.swift
> +    }
하나로 통합해서 관리하는 형태는 어떤 형태일까요?? 어떤식으로 코드를 표현할 수 있을가요?? 조금더 자세히 생각을 해보자면 어떤 컬랙션 타입을 사용할까요? 각각의 코드를 상대방에게 설명할때 이점과 단점에 대해서 알려주실 수 있을까요?

2022-04-27 08:49 UTC, GangWoon commented on sideDish/sideDish/View/FoodCell.swift
> +        }
테스트 용도가 아닐경우에 의미가 있는 코드일까요?

2022-04-27 08:49 UTC, GangWoon commented on sideDish/sideDish/View/FoodCell.swift
> +    }()
해당 프로퍼티를 외부로 노출할 필요가 있을까요? 접근 지정자에 대해서 말씀드리는게 아닌, 생성하고 원하는대로 꾸민 후에도 접근할 이유에 대해서 말씀드리는겁니다.

2022-04-27 08:49 UTC, GangWoon commented on sideDish/sideDish/View/FoodCell.swift
> +        imageView.image = UIImage()
의미가 있는 코드일까요?

2022-04-27 08:49 UTC, GangWoon commented on sideDish/sideDish/ViewController/MainViewController.swift
> +        }
해당 부분에서 어색함을 느끼셨을거 같습니다.

2022-04-27 08:49 UTC, GangWoon commented on sideDish/sideDish/ViewController/MainViewController.swift
> +        }
날것의 값이 아닌 코드를 읽는 사람에게 더 명확하게 표현할 수 있는 방법은 없었을까요?

2022-04-28 05:27 UTC, asqw887 commented on sideDish/sideDish/Model/FoodManager.swift
> +    }
결국에는 mainFood,soupFood,sideFood 모두 같은 타입을 가지고 있기 때문에 하나로 합치면 어떨까 고민해보았던 것이였습니다. 만약 하나로 통합하게 된다면 
1. 각 Food 객체에서 카테고리 분류를 위한 프로퍼티를 추가하고, 하나의 [Food] 배열로 관리. 
2. 카테고리를 key값으로 두어 하나의 딕셔너리 관리. 

> 각각의 코드를 상대방에게 설명할때 이점과 단점에 대해서 알려주실 수 있을까요?

이점: 각 역할에 대해 코드가 분리되어있어서 보기 편하고 다루기 편할 것 같다고 생각했습니다.
단점: 분리되어있다보니 역할이 다르다고 볼 수 있는점 문제인 것 같습니다.

2022-04-28 06:07 UTC, asqw887 commented
> 이전 피알에서 그려주신 구조에 대해서 작성하신 코드와 동일한지, 구현했을때의 이득이 무엇인지 점검하면 좋은 시기인거 같습니다.
해당 부분에 대해서 저한테 편하게 알려주셨으면 좋겠네요. 글로만 표현하기 어렵다면 다시 그림으로 표현하시거나, 말로 표현하셔도 괜찮습니다.

초기에 MVC 구조로 패턴을 결정하고, 저희가 판단하기에는 그에 맞게 코드를 작성했다고 느꼈습니다.
다만 아직 MVC가 각각의 역할만을 수행하고 있는지에 대해 이야기를 나눠보았는데, 현재 mainVC에서 `var foodManager: FoodManager = FoodManager()` 로 객체를 생성할때 데이터를 불러오는 작업을 FoodManager init에서 수행해주고 있어 이게 괜찮은 방법일지 의문이 들었습니다. 
이전에서 구현방법은 Model로 데이터가 들어오면 VC에게 알려주기위해 delegate나 NotificationCenter를 사용해서 알려주었는데, 초기 데이터 로드 작업도 이렇게 구현을 해야하는지 질문 드립니다...

2022-04-28 06:07 UTC, asqw887 commented
![이미지 2022  4  28  오후 3 01 (2)](https://user-images.githubusercontent.com/59790540/165687873-36d1ca19-6a7c-4fd9-99d3-160e57a41c5d.jpg)

2022-04-28 06:13 UTC, asqw887 commented
> 에러가 나는 상황을 콘솔에서만 알수 있다면, 사용자는 현재 앱의 상태가 문제가 발생했는지 명확하게 알 수 있을까요?? 문제가 발생한 상황에서 사용자에게 전달하려면 어떤 과정이 필요할까요? (너무 에러에 대해서 고민하실 필요는 없습니다.)

에러상황일 때 사용자의 입장에서는 생각하지 못했네요. 
저희가 생각해본 방법은 정확한 데이터가 들어오지 않았을 경우에는 그 데이터를 제외하고 뷰를 보여준다거나, 모달로 사용자에게 경고를 띄워주는 방법을 생각해봤습니다.

2022-04-28 06:21 UTC, asqw887 commented
> 컬랙션뷰에서 해당 셀을 꾸밀때 일반 뷰와 동일하게 꾸밀까요?? addsubview를 통해서 접근했나요? 일반적인 뷰와 다른점이 존재할 거 같은데 어떤 부분들이 다를까요??

FoodCell 을 만들 때 각각 컴포넌트를 contentView에 addSubview 해주는 방법으로 구현했습니다. 
질문을 잘 이해하지 못하겠는데.. 혹시 다시 한번 설명해주실 수 있을까요..? 😣

2022-04-28 06:55 UTC, asqw887 commented on sideDish/sideDish/ViewController/MainViewController.swift
> +        }
혹시 `foodManager.mainFood?.count` 에 직접 접근하는 것에 대해서 말씀하시는 건가요?
저희는 크게 어색함을 느끼지 못했습니다..

2022-04-28 07:01 UTC, asqw887 commented on sideDish/sideDish/View/FoodCell.swift
> +        imageView.image = UIImage()
이미지가 아직 로드 되지 않았을 때 디폴트로 UIImage() 를 보여주려고 한 의도였는데, 필요없는 코드네요.

2022-04-28 07:21 UTC, asqw887 commented on sideDish/sideDish/View/FoodCell.swift
> +    }()
외부로 노출할 필요가 없다고 판단했습니다. 후에 stackView에대해 접근이 필요하다면 public func 를 생성해서 접근하는 방향으로 할 계획입니다.

2022-04-28 07:26 UTC, asqw887 commented on sideDish/sideDish/Model/Food.swift
> +    private(set) var image: URL
헷갈릴 수도 있다는 생각이들어 `imageURL`로 프로퍼티 이름 수정하였습니다.

2022-04-28 08:54 UTC, JasonLee0223 commented on sideDish/sideDish/ViewController/MainViewController.swift
> +        }
Section을 enum타입으로 만들어 어떤 섹션인지 구분이 가게 리펙토링해보았습니다!

2022-04-28 13:42 UTC, GangWoon commented on sideDish/sideDish/Model/FoodManager.swift
> +    }
저는 단점을 많이 공감하진 않을 거 같습니다. 
이점이 더 크다고 생각해요.

2022-04-28 13:44 UTC, GangWoon commented on sideDish/sideDish/ViewController/MainViewController.swift
> +        }
날것의 값을 직접 사용하고 있지 않나요? 1, 2, 3 해당 값을 다른 의미있는 형태로 표현하려면 어떤 방법이 있을까요?

2022-04-28 13:48 UTC, GangWoon commented
ViewController는 무슨 역활을 할까요?
View가 자신이 언제 꾸며질지 정할까요?

데이터의 흐름을 누구이게 권한을 설정하며, 어느 시점에 실행할것인지 생각해보시면 좋을 거 같습니다.

콜랙션 뷰 셀은 재사용이 되나요?

2022-04-29 01:32 UTC, JasonLee0223 commented on sideDish/sideDish/Model/FoodManager.swift
> +    }
좋은 의견 감사합니다! 추후 조금 더 깊이 생각해보는 시간을 가져보도록 하겠습니다!

2022-04-29 01:35 UTC, JasonLee0223 commented on sideDish/sideDish/ViewController/MainViewController.swift
> +        }
Section을 enum타입으로 만들어 어떤 섹션인지 구분이 가게 리펙토링해보았습니다!

2022-04-29 03:09 UTC, JasonLee0223 commented
> ViewController는 무슨 역활을 할까요?

ViewController는 Model 과 View는 서로를 모르게하고 각자(Main,View)의 역할을 잘 수행할 수 있도록 중간에서 조율해주는 역할을 한다고 생각합니다.

> View가 자신이 언제 꾸며질지 정할까요?

View의 내부 속성들은 뷰가 생성될때(init 시점)에서 초기화 될것이고, 이는 결국 해당 View를 소유하는 ViewController의 View LifeCycle 메소드에 따라 결정된다고 생각했습니다.

> 데이터의 흐름을 누구이게 권한을 설정하며, 어느 시점에 실행할것인지 생각해보시면 좋을 거 같습니다.

ViewController가 권한을 설정하며 각각의 데이터 흐름에 맞춰 언제 실행할 지 알려 준다고 생각됩니다.

> 콜랙션 뷰 셀은 재사용이 되나요?

```swift 
guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: self.cellID, for: indexPath) as? FoodCell else { return UICollectionViewCell() }
```    
로 커스텀으로 만든 셀뷰를 재사용하도록 구현했는데 놓치는 부분이 있을까요? 현재 스크롤할때마다 발생하는 문제점이 뷰 셀이 재사용이 제대로 되지 않아서 발생하는 문제점일 수 도 있다고 생각했습니다. 스크롤이 될때 이전에 만든 컬렉션 뷰를 재사용하고 있어서 이전 데이터에 새로운 데이터가 append 되어서 보여주고싶은 데이터가 제대로 등장하지 않은 문제점이 발생하는듯 합니다..

2022-04-29 03:14 UTC, JasonLee0223 commented
@GangWoon 2주동안 부족한 코드내용에 좋은 comment를 남겨주셔서 감사합니다! 여러가지 방식으로 협업과정에서 생각의 폭을 넓힐 수 있었던 것 같습니다!🧐  comment에 대한 답변 및 학습을 통해 구현을 좀 더 많이 못한게 아쉽지만 원론적인 부분부터 생각하게되는 시간을 갖게되어 앞으로 프로젝트를 해나아가는데 많은 도움이 된 것 같습니다! 다시 한 번 감사의 말씀드리며 금요일 PR에 대한 내용을 구현하지못해 이번으로 마무리해야할 것 같습니다..😢 2주동안 정말 고생많으셨습니다! 감사합니다! ㅎㅎㅎ

2022-04-29 05:19 UTC, merged