[BE][team-33] Miller, Nathan - DDD 를 활용한 구조 개선 및 주문 기능 추가
codesquad-members-2022/sidedish pull request #151
Opened 2022-04-27 08:03 UTC by rxdcxdrnine

안녕하세요, Dan! 2주차 첫번째 PR 을 올린 Miller, Nathan 입니다 😀

이번 PR 에서는 아래와 같은 구현 사항이 있었습니다.

### 변경 사항

- 데이터베이스 스키마 수정 및 Enum 활용
(데이터베이스 내 할인 정보, 배송 정보 연관관계 M:N 매핑을 1:N 연관관계로 수정)
- `RowMapper` 를 활용한 N:1 연관관계 수동 매핑 제거 및 모든 엔티티 간 1:N 연관관계 매핑
- DDD 에 따라 aggregate 별로 패키지 분리

### 추가된 사항

- 반찬 단건 조회 및 추천 반찬 조회 기능 추가
- 반찬 주문 기능 추가
- 비즈니스 로직 내 예외 처리 추가 및 에러 메시지 응답 처리 구현

### API

- [프로젝트 링크](http://3.35.134.169/)
- api 링크
    - 실제 예시
        - [http://3.35.134.169/dishes?category=든든한-메인요리](http://3.35.134.169/api/dishes?section=%EB%93%A0%EB%93%A0%ED%95%9C-%EB%A9%94%EC%9D%B8%EC%9A%94%EB%A6%AC)
    - 목업
        - [https://documenter.getpostman.com/view/17061438/Uyr7HyZR](https://documenter.getpostman.com/view/17061438/Uyr7HyZR)

### 배포

- nginx의 reverse proxy 기능을 사용하여 api를 80 포트로 접근할 수 있게 구성하였습니다.

2022-04-27 08:06 UTC, nathan29849 commented on backend/deploy/back_deploy.sh
> +nohup java -jar build/libs/sidedish-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod &
추후 무중단 배포를 고려하여 특정 profile로 실행하도록 쉘 스크립트를 구성했습니다.

2022-04-27 08:08 UTC, nathan29849 commented on backend/src/main/resources/application.properties
> +spring.mvc.servlet.path=/api
80포트로 포트포워딩을 하기 위하여 API와 Client URL을 구분하였습니다.

2022-04-27 08:08 UTC, rxdcxdrnine commented on backend/src/main/java/com/codesquad/sidedish/dish/dto/DishListResponse.java
> +    }
DTO 내 null 인 필드를 만들기보다, 없는 경우에 empty string 으로 응답하도록 구성했습니다.
nullsafe 한 객체를 만들기 위해 로직을 위와 같이 구성했는데, 괜찮은 방법인지 궁금합니다.

2022-04-27 08:09 UTC, rxdcxdrnine commented on backend/src/main/java/com/codesquad/sidedish/other/DiscountPolicy.java
> +    }
자주 변경되지 않을 데이터를 테이블로 만들기보다 enum 으로 만들었습니다.

2022-04-27 13:19 UTC, Hyune-c commented on backend/deploy/back_deploy.sh
> +nohup java -jar build/libs/sidedish-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod &
`nit`
아마 ec2를 직접 사용하라는 제약 조건 때문에 이런 배포 방식을 선택하신 것 같습니다.
하지만 이렇게 스크립트를 통한 배포 방법은 상대적으로 올드한 방법입니다.
실무에서는 작은 스타트업이라도 ec2를 그대로 사용하기보다는 beanstalk 정도는 사용할 것이고, 
큰 기업이라면 devops를 두고 ecs, k8s 구성을 주로 하기 때문이죠.

만약 취직한 회사가 CI/CD 구성이 안되어 이렇게 스크립트로 하는 회사라면 beanstalk 구성 정도는 제안하는 것도 좋다고 생각해요.
즉 여유가 되셔서 한 것이라면 괜찮지만, 그렇지 않다면 백엔드 로직에 `선택과 집중`을 하시는게 좋다고 생각합니다.

2022-04-27 15:35 UTC, Hyune-c requested changes
수고하셨습니다.
매우 많은 생각과 고민이 보이는 코드여서 리뷰하는데 재미있었습니다.
하지만 다음에는 조금 더 짧은 pr로 부탁드려요.

2022-04-27 15:35 UTC, Hyune-c commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation:2.6.7'
`nit`
디펜던시 설정에 컨벤션이 있는 것은 아니지만, 보통 dependency scope 기준으로 묶거나 의미있는 그룹끼리 묶어 주석을 달곤 합니다.

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/dish/domain/Dish.java
> +    private Integer stock;
스키마 정의를 보니 디폴트를 0으로 주셨더라구요.
하지만 이것은 객체 정의의 하나라고 생각하는데 어떠신가요?

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/test/java/com/codesquad/sidedish/DishRepositoryTest.java
> +@ActiveProfiles({"dev"})
dev profile이 local 구성이기에 차용하신 것 같은데, dev 환경을 원격으로 구성해야된다면 어떻게 될까요?

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/other/DiscountPolicy.java
> +    }
`nit`
이왕 lombok을 사용하고 있다면 getter나 생성자 사용도 좋을 것 같아요.

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/exception/BusinessException.java
> +    }
좋은 접근 입니다. 👍

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/exception/GlobalExceptionHandler.java
> +    }
지금의 구성은 `RestControllerAdvice`를 충분히 사용하지 않고 있군요.
`ResponseStatus`를 활용해보는 것은 어떤가요?

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/exception/GoneException.java
> +public class GoneException extends BusinessException {
커스텀 예외는 이해를 돕기 위해 주석을 활용하면 좋을 것 같아요.
저는 이 예외가 이름만 보고는 바로 떠오르지 않아요.

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/test/java/com/codesquad/sidedish/DishRepositoryTest.java
> +        System.out.println(optional);
테스트 케이스는 출력이 아닌 단언문을 활용해주세요.
이것은 정상적인 테스트 케이스로 볼 수 없습니다.

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/other/page/Criteria.java
> +        this.page = Math.max(page, 1);
저는 실무에서는 주로 삼항연산자를 활용하는데, 알고리즘 풀면서는 이런 형태를 본 적이 있는 거 같아서 신기하네요 ㅎㅎ 👍

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/other/page/Criteria.java
> +public class Criteria {
`nit`
혹시 criteria라는 단어는 어디서 가져오신거죠?

이 클래스의 역할은 page 같은데, `JPA criteria query`와 명칭이 같아서 순간 헷갈렸네요.
처음에는 `jdbc dependency에 pageable이나 slice가 없어서 가져오신건가?` 했는데 찾아보니까 있더라구요.
혹시 커스텀하게 만들어주신 이유가 있을까요?

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/resources/sql/schema.sql
> +    dish_id     INT          NOT NULL AUTO_INCREMENT COMMENT 'dish 테이블의 레코드를 식별하기 위한 ID',
pk를 int로 설정하는 것과 long으로 설정하는 것의 차이는 무엇이 있을까요?

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/dish/dto/DishListResponse.java
> +    }
왜 `filter()`와 `findAny()`를 쓰나 했더니 `DishImage` 중 sequence가 1인 것을 가져오기 위함이군요.
지금 구현하신 형태는 솔직히 실무에서 종종 보이는 형태이긴 합니다만 좀 더 좋게 개선할 수 있을 것 같습니다. 

- dish에서 images를 가져와서 선별하는 것 보다 첫번째 이미지를 명시적으로 가져오는 것은 어떨까요?

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/dish/dto/DishListResponse.java
> +            .collect(Collectors.toList());
`nit` 
이렇게 map이 반복된다면, 메서드 참조를 포기하더라도 하나의 map으로 묶는 것이 좋을 수 있습니다.
또는 private 메서드로 분리할 수도 있죠.

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/category/dto/CategoryResponse.java
> +                .collect(Collectors.toList()));
dishListResponse의 생성 책임을 분리하는 것이 좋지 않을까요?

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/category/CategoryService.java
> +        List<Dish> dishes = dishRepository.findByIdIn(dishIds);
상당히 복잡하군요. 추측컨데 `rowmapper`의 삭제로 인해 `ref` 객체들이 service에서 조립되기 때문인 것 같습니다.

보통 `영속성 레이어에는 로직이 없는 것이 좋다`고 말합니다.
하지만 반대로 `단순 매핑이 도메인 레이어에 존재해야 될까? ` 도 고민할 수 있을 것 같습니다.

아마 저라면 `ref` 작업을 repository에서 한 후 결합된 dto를 반환했을 것 같아요.
보통 실무에서는 이런 R 성 작업을 쿼리나 qeurydsl로 하여 projection된 dto를 만들기도 합니다.

`projection`이라는 키워드를 공부해보시면 좋을 것 같습니다.

2022-04-27 15:35 UTC, Hyune-c commented on backend/src/main/java/com/codesquad/sidedish/dish/domain/Dish.java
> +            .reduce(BigDecimal.ONE, BigDecimal::multiply);
`nit`
무엇을 하시려는지 메서드명이나 느낌으로는 알겠는데, 반복적인 map의 단점은 가독성이 떨어집니다.
오히려 이렇게 반복되는 경우는 메서드 참조를 포기하고 map을 묶는 것도 방법입니다.

2022-04-28 07:51 UTC, merged

2022-04-29 02:26 UTC, rxdcxdrnine commented on backend/src/main/java/com/codesquad/sidedish/dish/dto/DishListResponse.java
> +    }
이전에 `RowMapper` 를 사용해 `Dish` 테이블과 `DishImage` 테이블 간에 N:1 연관관계 매핑 시에 말씀하신 것처럼 첫번째 이미지만 가져와서 DTO 에 추가했습니다. 하지만 현재 Spring Data JDBC 에서 aggregate 별로 데이터를 가져오다보니, 1:N 으로 연관관계를 매핑해서 가져오게 되었습니다.

만약 Spring Data JPA 와 같이 N:1 연관관계 매핑이 지원되는 데이터 모듈을 사용하면 말씀하신 것처럼 첫번째 이미지를 가져오는 것으로 처리할 수 있을 것 같습니다.

2022-04-29 02:29 UTC, rxdcxdrnine commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation:2.6.7'
디펜던시를 추가하기 위해 maven repository 의 코멘트를 직접 가져오면서 디펜던시에 대한 정보인 주석도 추가하면 좋을 것 같다고 생각했는데, 필요하지는 않았던 것 같습니다.

말씀하신 것처럼 앞으로는 관련있는 디펜던시 그룹을 주석으로 작성하겠습니다!

2022-04-29 02:33 UTC, rxdcxdrnine commented on backend/src/main/java/com/codesquad/sidedish/dish/domain/Dish.java
> +    private Integer stock;
말씀하신 것처럼 스키마에서 디폴트 값을 0 으로 지정했는데 객체에서 기본값은 null 이네요..! 수정하겠습니다

2022-04-29 02:36 UTC, rxdcxdrnine commented on backend/src/test/java/com/codesquad/sidedish/DishRepositoryTest.java
> +@ActiveProfiles({"dev"})
`dev` 환경을 원격에서 사용한다면, `local` 프로필을 별도로 만들고 해당 프로필의 프로퍼티로 구성된 환경을 로컬 환경에서 사용해야할 것 같습니다! 네이밍을 수정하겠습니다.

2022-04-29 02:38 UTC, rxdcxdrnine commented on backend/src/main/java/com/codesquad/sidedish/other/DiscountPolicy.java
> +    }
왜 enum 에서만 `@Getter` 를 활용을 하지 않았는지 이해가 안되네요..! 감사합니다

2022-04-29 02:39 UTC, rxdcxdrnine commented on backend/src/main/java/com/codesquad/sidedish/exception/GoneException.java
> +public class GoneException extends BusinessException {
Http 응답 시 사용할 status 의 이름을 비즈니스 예외 처리 시에 사용했는데, 좋지 못한 방법인 것 같습니다. 네이밍에 더 신경을 쓰도록 하겠습니다.

2022-04-29 02:41 UTC, rxdcxdrnine commented on backend/src/test/java/com/codesquad/sidedish/DishRepositoryTest.java
> +        System.out.println(optional);
이번 PR 에서도 제대로된 테스트 없이 개발을 진행한 것 같습니다.. 죄송합니다

2022-04-29 02:43 UTC, rxdcxdrnine commented on backend/src/main/java/com/codesquad/sidedish/exception/GlobalExceptionHandler.java
> +    }
ExceptionHandler 에 ResponseStatus 를 활용할 생각을 하지 못했는데, 감사합니다!

2022-04-29 02:53 UTC, rxdcxdrnine commented on backend/src/main/java/com/codesquad/sidedish/other/page/Criteria.java
> +public class Criteria {
이전에 Spring Data 모듈 없이 Spring Boot 에서 기본적으로 지원하는 JDBC 만 사용했을 때, `Pageable` 과 `Slice` 을 지원하지 않았기 때문에 페이징을 위해 `criteria` 라는 이름의 페이징과 관련한 정보를 담는 클래스를 만들어 사용했습니다.

말씀하신대로 현재 사용하는 Spring Data 모듈은 `Pageable` 과 `Slice` 을 지원하기 때문에 필요하지는 않다고 생각합니다!

2022-04-29 03:00 UTC, rxdcxdrnine commented on backend/src/main/resources/sql/schema.sql
> +    dish_id     INT          NOT NULL AUTO_INCREMENT COMMENT 'dish 테이블의 레코드를 식별하기 위한 ID',
먼저 PK 값이 2^16 을 넘어가는 경우에는 `bigint` 타입의 사용을 반드시 고려해야합니다. `int` 형은 4바이트 (32비트) 의 숫자를 저장할 수 있고, `bigint` 형은 8바이트 (64비트) 의 숫자를 저장할 수 있기 때문입니다.

하지만 그렇지 않다면, 고려할 수 있는 사항이 몇가지 있을 것 같습니다. 먼저 `int` 타입은 기본적으로 `bigint` 에 비해 용량을 적게 차지하고 연산을 더 빠르게 처리할 수 있습니다. 그렇다고 반드시 `int` 형으로 만들어야하는 것은 아니고, 데이터베이스 내 타입의 업그레이드 가능성을 생각하고 정해야합니다.

2022-04-29 03:01 UTC, rxdcxdrnine commented on backend/src/main/java/com/codesquad/sidedish/dish/dto/DishListResponse.java
> +            .collect(Collectors.toList());
메서드 레퍼런스를 사용하면 가독성이 더 좋을 것이라고 생각하고 `map` 하나로 묶기보다 반복적으로 `map` 을 활용했습니다.

2022-04-29 03:22 UTC, rxdcxdrnine commented on backend/src/main/java/com/codesquad/sidedish/dish/domain/Dish.java
> +            .reduce(BigDecimal.ONE, BigDecimal::multiply);
메서드 레퍼런스를 사용하면 가독성이 더 좋을 것이라고 생각하고 map 하나로 묶기보다 반복적으로 map 을 활용했습니다. 팀원 간의 논의 끝에 기존의 방식대로 유지해보겠습니다.