[TEAM-24] [땃쥐, Lee] BE 세번째 PR입니다.
codesquad-members-2022/sidedish pull request #161
Opened 2022-04-27 08:38 UTC by ttasjwi

## 안녕하세요!
[TEAM-24] [땃쥐, Lee] 백엔드 3번째 PR입니다.

안녕하세요 브라이언! 24조 백엔드 땃쥐, Lee입니다.
3번째 PR을 보내드립니다.

## 배포 URL
http://15.165.236.13

## API 명세
https://github.com/sungju-kim/sidedish/wiki/%EB%B0%B1%EC%97%94%EB%93%9C-API-%EB%AA%85%EC%84%B8

## 작업 내역
- [x] `Item`, `Order`, `Delivery의` 저장계층(Repository) 구현
    - `Item`의 경우 요구사항에 상품 추가 로직이 없어서 `save()` 메서드는 따로 구현하지 않고, 하드코딩한 더미 데이터를 활용해 클라이언트와 연결하도록 구현했습니다.
    - `OrderRepository`의 경우 자바 코드상에서 필드로 들고 있는 객체들도 Select 해 오면서 생성해 주어야 해서 여러 빌더 메서드들이 붙게 되었는데요. 저희가 Spring Data JDBC를 사용하지 못하고 일반 JDBCTemplate을 사용하면서 생긴 불편함인 것 같습니다. JPA를 조금 더 중점적으로 학습하며 이후 미션에서는 이런 부분들을 개선해나가려고 합니다.
- [x] `ItemService` 클래스 구현
    - `itemId`를 인자로 받아 해당 `id`값에 해당하는 `ItemDetailResponse` DTO를 리턴하는 `findOne()` 메서드와, 인자로 들어온 섹션에 해당하는 `ItemListResponse` DTO를 리턴하는 `findBySection(...)` 메서드를 구현했습니다.
    
---

## 현재 코드에서 부족하다고 느끼는 것들
- 시간부족으로 도메인의 일부 로직들에 대한 테스트코드를 작성하지 못 했습니다.
- 시간부족으로 당장 기능에서 필요한 로직들에 해당하는 메서드들만 구현했습니다. 제대로 된 테스트를 하려면 모든 엔티티들에 대한 Save, Find 메서드를 구현해야했습니다. 실제로 테스트코드에서는 트랜잭션에서 테스트상품을 추가하고 그것을 기반으로 테스트를 해야했는데, data.sql에서 등록한 요소들의 존재를 전제로하여 테스트가 진행되고 있습니다.
- 기능구현에서 충분한 예외처리가 수행되지 못 하고 있다. 예외를 던지기만 하지, 예외를 어떻게 처리할지는 구현하지 못 하고 있다. 인터셉터 등 Spring에서 지원하는 예외처리 기능을 충분히 학습해야겠습니다.
- Spring-Data-Jdbc을 사용했으면 편리하게 처리할 수 있었을 법한 로직들도 있었으나, 당장 이에 대해 익숙하지 못 해 그냥 쿼리를 손수 짜서 날렸습니다...
- 상품과 상품이미지 사이에는 1:多 관계가 있는데 이를 SELECT 해올 때 rowMapper에서 쿼리를 날려오는 식으로 처리했습니다. 이를 어떻게 처리했으면 좋을지는 아직 고민 중입니다.

---

2022-04-27 23:09 UTC, wheejuni requested changes
수고하셨습니다 💯 
몇 가지 의견 남깁니다. 확인 및 반영 부탁드려요

2022-04-27 23:09 UTC, wheejuni commented on BE/src/main/java/codesquad/sidedish/domain/delivery/DeliveryRepository.java
> +        return jdbcTemplate.query(selectDeliverySql, parameters, deliveryRowMapper()).stream().findFirst();
`.findFirst()` 한 후 `.orElseThrow()` 등 예외처리까지 여기서 마무리하면 어떨까 싶습니다.

2022-04-27 23:09 UTC, wheejuni commented on BE/src/main/java/codesquad/sidedish/domain/item/Item.java
> +            throw new IllegalArgumentException(
별도의 예외가 있으면 좋겠습니다! 예외 이름은 뭐가 좋을까요...

2022-04-27 23:09 UTC, wheejuni commented on BE/src/main/java/codesquad/sidedish/domain/item/Item.java
> +        return (int)(getDiscountedItemPrice() * 0.01);
`0.01` 이라는 숫자가 어떤 의미를 갖는지를 정확히 변수로써 나타내야 한다고 봅니다.

2022-04-27 23:09 UTC, wheejuni commented on BE/src/main/java/codesquad/sidedish/domain/item/Item.java
> +                .filter(itemImage -> itemImage.getItemImageType() == ItemImageType.MAIN)
`ItemImage` 클래스에 메인 이미지 여부를 판별하는 메소드가 있으면 좋겠군요.
게터를 불러서 꺼내온 다음 등호로 비교하지 말고요.

2022-04-27 23:09 UTC, wheejuni commented on BE/src/main/java/codesquad/sidedish/domain/item/Item.java
> +                .filter(itemImage -> itemImage.getItemImageType() == ItemImageType.SUB)
여기도 같은 의견 드립니다

2022-04-27 23:09 UTC, wheejuni commented on BE/src/main/java/codesquad/sidedish/domain/member/Member.java
> +    }
단순히 마일리지를 더하기 처리만 해주면 되는 걸까요? 이력 관리는 없어도 될까요?
회원의 마일리지 가감 이력을 모두 보관하고 있다가, 그 회원의 마일리지 합을 알고 싶으면 그걸 `.sum()` 하는 방향이 좋을 것 같은데..
어떻게 생각하세요?

2022-04-27 23:09 UTC, wheejuni commented on BE/src/main/java/codesquad/sidedish/service/ItemService.java
> +                () -> new NoSuchElementException("해당하는 id의 상품이 없습니다.")
여기도 이 상황에 맞는 예외가 있어야 할 것 같습니다!
프로젝트 전역으로 `404` 에 해당하는 예외를 설계하시는 것도 좋아요

2022-04-28 01:49 UTC, ttasjwi commented on BE/src/main/java/codesquad/sidedish/domain/item/Item.java
> +        return (int)(getDiscountedItemPrice() * 0.01);
막 써놓고보니 매직넘버군요. 별도로 필드에 static 상수를 선언해봐야겠습니다.

2022-04-28 01:50 UTC, ttasjwi commented on BE/src/main/java/codesquad/sidedish/domain/item/Item.java
> +                .filter(itemImage -> itemImage.getItemImageType() == ItemImageType.MAIN)
이미지에 있어 메인이미지냐, 서브이미지냐 판단하는 로직을 자체적으로 부여하면 자율성이 늘어날 것 같긴합니다. 이건 반영해보겠습니다!

2022-04-28 01:52 UTC, ttasjwi commented on BE/src/main/java/codesquad/sidedish/domain/member/Member.java
> +    }
이력관리... 이번 미션의 시간관계상 거기까지 바로 구현하기 힘들 수 있을 것 같습니다. 다른 것들을 먼저 구현해보고 시간적 여유가 있으면 반영해보도록 하겠습니다.  ㅜㅜ

2022-04-28 07:15 UTC, street62 commented on BE/src/main/java/codesquad/sidedish/domain/item/Item.java
> +            throw new IllegalArgumentException(
이 경우에는 NotEnoughStockException으로 정의했습니다!

2022-04-28 07:16 UTC, street62 commented on BE/src/main/java/codesquad/sidedish/domain/item/Item.java
> +                .filter(itemImage -> itemImage.getItemImageType() == ItemImageType.SUB)
이 경우에는 `ItemNotFoundException`으로 정의했습니다!

2022-04-28 07:19 UTC, street62 commented on BE/src/main/java/codesquad/sidedish/service/ItemService.java
> +                () -> new NoSuchElementException("해당하는 id의 상품이 없습니다.")
이 경우에는 ItemNotFoundException으로 정의했습니다!

2022-04-28 07:23 UTC, ttasjwi commented on BE/src/main/java/codesquad/sidedish/domain/delivery/DeliveryRepository.java
> +        return jdbcTemplate.query(selectDeliverySql, parameters, deliveryRowMapper()).stream().findFirst();
이 부분은 서비스 로직 등에서 처리하도록 하는게 편할 것 같아서 우선 그대로 두었습니다.

2022-04-28 15:55 UTC, merged