[team-32][BE][선을로&헤이호] 4번째 PR 요청
codesquad-members-2022/sidedish pull request #167
Opened 2022-04-27 10:02 UTC by fpzk5656

안녕하세요. BE 32팀 선을로, 헤이호 입니다.

지난 번 PR에서 리뷰 해주신 내용을 살펴보며 코드를 수정 해보았습니다.
의도하셨던 바와 다르게 해석하여 진행한 부분이나, 추가로 부족한 부분들을 지적 해주시면 감사 하겠습니다.
매 번 꼼꼼하게 리뷰 남겨주셔서 감사합니다.👍

2022-04-27 10:42 UTC, dongkyu-park commented on be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
> +	}
`service` 레이어의 테스트코드를 만드려면  `controller`와 `repository`를 분리하는 것이 먼저다. 라는 내용을 보아서 해당 방식으로 테스트를 했습니다.

지금 `service` 레이어에서 하는 일은 거의 없고 단순히 `repository`의 메서드를 호출하는 역할만 갖고 있는데 그래서인지 `repositoryTest`에서 테스트한 동일한 내용을 똑같이 복붙 하는 느낌을 받았습니다. 

레이어를 분리해서 테스트 하는거니 각각의 레이어에서 동일한 작업을 반복해도 괜찮은걸까요? 아님 뭔가 방법을 바꾸어야 할까요?

2022-04-27 10:45 UTC, dongkyu-park commented on be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
> +	void loadSideDishListByType_test1() {
카테고리별 조회에서 `respository` 호출을 제외하고 `service` 레이어가 하는 일은 이것 밖에 없는 것 같아요. 

나머지 데이터에 대한 테스트는 `repository`에서 체크를 하고 있으니 `serviceTest` 코드에선 제외해주는 것이 좋을까요, 

아니면 레이어를 분리했기 때문에 각각 모두 해주는 것이 맞을까요?

2022-04-27 10:49 UTC, dongkyu-park commented on be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
> +	}
`repository`와 분리해서 결과로 가져올 더미데이터를 따로 만들어 주었는데, 하면서도 의문이 많이 들었던 방법인데.. 옳게 된 방법인지 궁금합니다.

2022-04-27 10:52 UTC, dongkyu-park commented on be/src/main/java/kr/codesquad/sidedish/response/ErrorCode.java
> +	PRODUCT_QUANTITY_insufficient(HttpStatus.BAD_REQUEST, "현재 상품의 재고가 요청한 값보다 부족합니다."),
DB에 저장 된 상품의 재고가 주문갯수보다 적은 경우는 클라이언트의 요청값이 잘못 되었다는 느낌과는 조금 다른 것 같은데, `BAD_REQUEST` 응답코드가 적절 할까요? 

500도 조금 이상한 느낌이고.. 이런 값이 들어올 경우 어떤 상태코드를 보내주면 좋을까요?

2022-04-27 16:43 UTC, Hyune-c requested changes
수고하셨습니다.

> 1) 멤버 한 두개 정도의 변경사항이면 setter를 써도 상관이 없는지에 대해 여쭙고 싶습니다.

- 네. 실제로 JPA entity는 setter를 허용합니다. (더티 체킹)
- 불변성은
    - 부수효과를 방지하며 로직이 일관성을 가집니다.
    - 객체를 매번 생성하는 비용이 듭니다.
    - 필드가 많아지거나 깊은 복사를 구현해야하는 경우 어려움이 있습니다.

`setter는 무조건 나쁘다`보다는 어떤 경우에 왜 나쁜지 알고 필요에 따라서는 사용해야될 수도 있습니다

> 2) PK 타입을 Integer로 한것과 Long으로 하는 것 중에 뭐가 더 좋냐

지금의 프로젝트에서는 Integer로 충분하지만 실무에서는 Long을 강력히 권장합니다.

https://dogleg.co.kr/?p=163

![image](https://user-images.githubusercontent.com/55722186/165575253-cc6a6b89-2200-47f2-9059-32078282ba9b.png)

2022-04-27 16:43 UTC, Hyune-c commented on be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
> +		);
저는 allMatch()만 썻는데 이것도 좋네요. 👍

2022-04-27 16:43 UTC, Hyune-c commented on be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
> +		List<ProductDTO> sideDishProductDTOS = productService.loadDishListByType(sideDishType);
`nit`
이건 컨벤션마다 다르긴 한데 저는 보통 `sideDishProductDtos`로 본 것 같아요.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
> +	}
개인적으로는 레이어별로 딜리버리만 하는 것을 mock으로 체크만 하는 것이라면 굳이 레이어별로 모두 테스트가 있어야되나 싶어요.
아마 저라면 service 테스트만 유지할 것 같습니다.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/test/java/kr/codesquad/sidedish/domain/SideDishTypeTestType.java
> +    }
```java
final CustomException exception = assertThrows(CustomException.class, () -> SideDishType.stringToEnum(sideDishType));
assertThat(exception).hasMessageContaining(ErrorCode.SIDE_DISH_TYPE_NOT_ALLOWED.getDetail());
```

저는 보통 이렇게 작성하곤 하는데 지금의 것이 assertj를 쓰고 하니 더 좋다는 느낌도 드네요. 👍

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	@GetMapping(value = {"/{dishType}", "/{dishType}/{sideDishType}"})
api 2개가 온전히 같은 로직으로 작동한다면 설계가 잘못된 것이 아닐까요..?
중복 로직이라고 생각할 수도 있지만 분리하는 것이 좋다고 생각합니다.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
>  		@PathVariable String dishType,
dishType은 enum으로 존재하는데 굳이 String이어야 하나요?

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		@PathVariable(required = false) Optional<String> sideDishType) {
아마 2개의 api를 받기 위해 Optional을 활용하신 것으로 추정됩니다.
api를 분리하는 것이 더 좋다고 생각합니다.

심지어 이 sideDishType은 dishType과 접미사가 같아 Optional을 표현하지 못하고 있습니다.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	private CommonResponse OKCommonResponse(Object data) {
- 메서드는 컨벤션 상 소문자로 시작해야 합니다.
- 이것은 이 컨트롤러에서만 쓰이는 것이 아닌 공통 메서드의 역할이라고 생각합니다.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		checkForExistingId(id);
단순한 숫자 레인지 체크라면 spring에서 제공하는 validatiaon을 활용하면 좋을 것 같습니다.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
>  	public ResponseEntity<CommonResponse> order(@RequestBody RequestProduct requestProduct) {
`RestController`를 쓰고 있다면 `ResponseEntity`도 빼보는 것은 어떨까요?

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/SideDishType.java
> +    public static SideDishType stringToEnum(String type) {
굳이 매개변수가 string임을 명시할 필요가 있을까요?
만약 지금의 형태라면`intToEnum`, `longToEnum` 등 매개변수의 변화가 생길 때마다 메서드명도 변경이 필요할 것입니다.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/SideDishType.java
> +    private final String type;
type보다는 name에 가깝지 않을까요?

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/ShippingInfo.java
> +	private final Integer deliveryType;
deliveryType은 이미 enum으로 존재하는데 같은 이름이 interger로 사용되고 있네요..?

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/DiscountType.java
>  		}
SideDishType에서 하신 것을 생각하면 이 switch문을 좀 더 개선할 수 있을 것 같습니다.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
>  	}
이것들을 굳이 String으로 비교해야 할까요? enum을 만들었으니 활용할 수 있을 것 같습니다.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/exception/CustomException.java
> +    }
👍

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/repository/MemoryProductRepository.java
> +public class MemoryProductRepository {
`nit`
ProductRepository가 빠졌군요.. 아쉽습니다.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/response/CommonCode.java
> +	SUCCESS_NO_CONTENT(HttpStatus.OK, "요청에 성공했으나 응답할 데이터가 없습니다."),
```suggestion
	SUCCESS_NO_CONTENT(HttpStatus.OK, HttpStatus.NO_CONTENT.getReasonPhrase()),
```

`nit`
저라면 걍 이렇게 퉁쳤을 것 같기도 해요.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/response/ErrorCode.java
> +	PRODUCT_QUANTITY_insufficient(HttpStatus.BAD_REQUEST, "현재 상품의 재고가 요청한 값보다 부족합니다."),
5xx는 서버에서 예상하지 못한 에러여야 합니다.
400은 controller단의 에러이기에 어울리지 않아요.

아마 저라면 409를 활용할 것 같습니다.

2022-04-27 16:43 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/service/ServiceValidator.java
> +}
검증 책임을 모으셨네요. 꽤 좋은 접근 방법입니다. 👍

좀 더 나아가자면 각 행위별 검증을 class로 분리할 수 있습니다.
- SRP를 준수하게 되고
- validator를 주입할 수 있게 됩니다.
- 검증과 변경의 경계를 나눌 수 있습니다.

2022-04-28 06:04 UTC, dongkyu-park commented on be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
> +		);
모르고 사용했는데 allMatch() 키워드를 말씀 해주셔서 두 개의 차이점에 대해 알아보니 allSatisfy()는 조건에 부합하는 요소의 실패 메세지를 더 상세히 확인할 수 있다는 내용을 찾았습니다. 감사합니다!

https://stackoverflow.com/questions/53526156/assert-same-condition-on-all-elements-of-a-collection

2022-04-28 06:06 UTC, dongkyu-park commented on be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
> +		List<ProductDTO> sideDishProductDTOS = productService.loadDishListByType(sideDishType);
DTOS의 네이밍에 대한 이야기를 해주신걸까요?

2022-04-28 06:54 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		checkForExistingId(id);
@Validated @Min @Max 를 사용해서 처리하는 것으로 변경하였습니다!

2022-04-28 07:01 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/domain/ShippingInfo.java
> +	private final Integer deliveryType;
해당 enum의 상수를 결정 짓는 변수라 동일하게 지었었습니다;;
`deliveryForm`이라는 이름으로 변경 하였습니다.

2022-04-28 07:02 UTC, Hyune-c commented on be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
> +	}
네. 지금은 최선인 것 같아요.
비슷한 방법으로는 `ParameterizedTest`를 `MethodSource`와 사용할 수 있습니다.

만약 `테스트를 위한 초기 데이터를 만드는 것`이 일정 범위 이상 커지면 데이터 초기화 스크립트를 만들기도 합니다.
하지만 사이드 프로젝트에서는 그냥 이렇게 하는 것도 괜찮은 거 같아요.

2022-04-28 07:03 UTC, dongkyu-park commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		@PathVariable(required = false) Optional<String> sideDishType) {
>  sideDishType은 dishType과 접미사가 같아 Optional을 표현하지 못하고 있습니다.

이 부분 제대로 이해를 못 했는데, 추가 설명을 부탁드려도 될까요?

2022-04-28 07:04 UTC, Hyune-c commented on be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
> +		);
네. 맞아요.
하지만 `allSatisfy` 는 안에 assert를 또 만들어야되니 귀찮아서 전 걍 `allMatch` 쓸거 같긴 하네요 ㅋㅋ

2022-04-28 07:04 UTC, Hyune-c commented on be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
> +		List<ProductDTO> sideDishProductDTOS = productService.loadDishListByType(sideDishType);
넹. 카멜 케이스

2022-04-28 07:05 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/repository/MemoryProductRepository.java
> +public class MemoryProductRepository {
spring data jdbc 특유의 `CrudRepository` 라는 객체를 ProductRepository에 확장하니까 자동으로
그걸 implements 받고 있는 메모리 레포지터리에 CrudRepository에 있는 메소드까지 강제 해서 지웠습니다.

메모리 레포지터리는 만들었으면 언제든 쓸 수 있게 놔둬야하는 필요성을 중요하게 생각 안했었네요..
추상클래스를 만들어 어댑터 패턴으로 구현해보겠습니다!

2022-04-28 07:07 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		@PathVariable(required = false) Optional<String> sideDishType) {
- `String dishType` `Optional<String> sideDishType` 
    - 같은 접미사인데 하나는 그냥 String이고 하나는 Optional String 입니다.
    - 서로 다른 형을 같은 접미사로 대체하고 있습니다.
    - Type이라는 접미사는 보통 enum에 사용되는데 String에 사용되고 있습니다.

2022-04-28 07:08 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/repository/MemoryProductRepository.java
> +public class MemoryProductRepository {
네. querydsl에 관련된 김영한님 강의에서 어댑터 패턴을 본 기억이 나네요.
참고하시면 될거 같습니다.

2022-04-28 07:08 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/service/ServiceValidator.java
> +}
각 행위별 검증을 class로 분리할 수 있다는 말씀은

예를 들어 Service class가 여러개일 때
각 Service  별 공통된 행위의 메소드를 검증하는 하나의 validator class를 만들어서 관리하기도 한다는 말씀이실까요?

2022-04-28 07:11 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/ShippingInfo.java
> +	private final Integer deliveryType;
혹시 이거 enum의 ordinal을 사용하는 건가요?
맞다면 이 부분을 좀 더 공부해보셔야될거 같아요.

2022-04-28 07:14 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/service/ServiceValidator.java
> +}
지금이 그런 형태인 것 같구요.
각 행위별로 validator class를 만든다 함은, `상품 등록 검증` `상품 삭제 검증`과 같이 분리하는 것을 말합니다.
이렇게 하면 validator를 주입할 수 있게 되는데요.

테스트를 만들 때 검증을 항상 성공하는 mock validator를 만들어서 테스트를 편하게 할 수 있겠죠.
랜덤 로직을 테스트할 때 쓸 수 있는 기법입니다.

2022-04-28 07:21 UTC, dongkyu-park commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		@PathVariable(required = false) Optional<String> sideDishType) {
아아아.. 감사합니다!

2022-04-28 07:52 UTC, merged