[team-25 데이먼/벅픽] 2주차 수요일 PR요청
codesquad-members-2022/sidedish pull request #172
Opened 2022-04-28 02:19 UTC by dukcode

안녕하세요 브라이언 저번 PR 요청하고 연락을 안드려서 지금까지 작업했던 내용 바로 PR 요청드립니다.

리뷰 주신내용은 작업이 된 상태라서 빠르게 적용하고 PR 요청드립니다.

[배포 URL](http://3.38.240.18:8080/)
[API 문서 URL](http://3.38.240.18:8080/swagger-ui/index.html)

## 작업내역

* [x] Repository 레이어, Controller 레이어 구현
* [x] 예외 및 Validation 처리
* [x] Swagger 적용
* [x] AWS 배포

## 추후 작업할 내용

* 리팩토링
* 테스트 코드 구현
* OAuth2 구현

2022-04-29 13:56 UTC, wheejuni requested changes
수고 많으셨습니다~ 💯 몇가지 의견 드립니다.

2022-04-29 13:56 UTC, wheejuni commented on BE/src/main/java/com/team25/sidedish/controller/CategoryController.java
> +                .map(CategoryResponse::from)
도메인 클래스 <-> DTO 변환을 어디에서 해야 하는지는 많은 논란이 있는데요...
개인적으론 `Service` 에서 하는 것을 선호하기는 합니다. 제가 그렇게 생각하는 이유들이 있는데 아래 키워드들을 학습하시고 같이 고민해보면 좋을 것 같군요.

- lazy loading
- OSIV(OEIV)

2022-04-29 13:56 UTC, wheejuni commented on BE/src/main/java/com/team25/sidedish/domain/Delivery.java
> +    public static int FREE_PRICE = 40_000;
배달료, 무배 주문금액도 변경 가능성이 있는 요소 아닐까요? 그렇게 설계해야 하지 않을까요?

2022-04-29 13:56 UTC, wheejuni commented on BE/src/main/java/com/team25/sidedish/domain/Product.java
> +        return (int) ((1-discountRate) * price);
연산자 앞뒤로 한 칸씩 스페이스 넣어 주시면 좋겠네요~

2022-04-29 13:56 UTC, wheejuni commented on BE/src/main/java/com/team25/sidedish/domain/Product.java
> +    }
잘 이해가 가지 않습니다~ `price` 를 인스턴스 변수로 관리하고 있는데 왜 다시 파라메터를 받아야 하는 건가요?

2022-04-29 13:56 UTC, wheejuni commented on BE/src/main/java/com/team25/sidedish/dto/response/ErrorResponse.java
> +    private final List<String> messages;
하나의 에러에 메세지가 여러개 발생할 수 있는 건지요?
그래야 할 이유가 잘 생각나지 않습니다.

2022-04-29 13:56 UTC, wheejuni commented on BE/src/main/java/com/team25/sidedish/service/CategoryService.java
> +        }
https://stackoverflow.com/questions/12182809/spring-data-crudrepository-exists
이런 접근법이 낫지 않을까 생각해 봅니다.

2023-02-08 02:04 UTC, honux77 commented
오래된 PR이라 제가 닫겠습니다. 브라이언, 데이먼, 벅픽 모두 수고하셨습니다.

2023-02-08 02:04 UTC, merged