[team-06][FE] Header Component 생성
codesquad-members-2022/sidedish pull request #26
Opened 2022-04-20 08:00 UTC by bcad1591

## ☑진행상황

- CRA기반 개발환경 세팅 + Mocking 라이브러리 MSW 설치
- Header영역 컴포넌트 구현

## ☑어려웠던 점

분리해서 CSS작성하다보니까 Styled Component가 많이 어색하고 익숙해지기가 힘들었습니다. 컴포넌트의 최상단 Style Tag 이름을 Root로 통일하여 작성하였습니다.

2022-04-20 22:22 UTC, crongro requested changes
수고하셨어요~ 리뷰 참고하시고요.
초반 설정이 잘 된 듯 하니 컴포넌트 추가하면서 개발해보세요.

2022-04-20 22:22 UTC, crongro commented on fe/README.md
> +# Getting Started with Create React App
readme 지우시고 새로 만들어보세요~

2022-04-20 22:22 UTC, crongro commented on fe/src/Header/Header.jsx
> +    <Root>
Root 라는 표현은 모든것의 최상위 개념을 일컫거든요.
그런데 이 컴포넌트내에서의 상위 래퍼역할이니까, root 보다는 HeaderWrapper 라던가.. 요런 이름으로 하면 좋겠어요.

2022-04-20 22:22 UTC, crongro commented on fe/src/Header/Menu.jsx
> +    <Root>
여기도 Root 대신에
NavListStyled 라던가 이렇게 해도 될듯.

2022-04-20 22:22 UTC, crongro commented on fe/src/Header/Menu.jsx
> +    color: ${'#777777'};
#777 로 단축표기법으로.

2022-04-20 22:22 UTC, crongro commented on fe/src/Header/Menu.jsx
> +    font-size: 14px;
나중에는 자주 사용되는 스타일은 global style로 설정할 수 있을겁니다.
중복이 되면 나중에 해보세요

2022-04-20 22:22 UTC, crongro commented on fe/src/Header/Menu.jsx
> +          {subMenuList.map((subMenu, idx) => (
map 잘 사용하셨어요.
이런 javascript 코드가 길어지면 return 위에서 결과를 만들고 여기에 결과만 표현하는 것도 방법입니다.
jsx가 간결해보이도록요.

2022-04-20 22:22 UTC, crongro commented on fe/src/Header/MenuList.jsx
> +  const [menuDatas] = useState([
이 값은고정된 값으로 상태관리가 필요없는 값 같네요.
따라서 useState라고 하지않고, 그냥 변수로 담아두고 사용하세요.
MenuList 함수 위에 분리하는 것이 더 나을 것 같고요.

2022-04-20 22:22 UTC, crongro commented on fe/src/Header/MenuList.jsx
> +  const [subMenuOpen, setSubMenuOpen] = useState(false);
네 요건 상태관리가 필요한 것이죠. 잘했습니다.

2022-04-20 22:22 UTC, crongro approved these changes

2022-04-20 22:22 UTC, crongro commented
머지합니다.(실수로 request change 를 해버렸네요)

2022-04-20 22:22 UTC, merged

2022-04-21 03:07 UTC, bcad1591 commented on fe/src/Header/Header.jsx
> +    <Root>
반영하겠습니다~