[TEAM-24] [땃쥐, Lee] BE 첫번째 PR입니다.
codesquad-members-2022/sidedish pull request #30
Opened 2022-04-20 08:04 UTC by street62

안녕하세요 리뷰어님. 24팀 백엔드를 맡은 땃쥐, Lee입니다.
첫 번째 PR을 보내드립니다.

이번 PR에서는 코드 상으로 구현한 내용은 아직 많지 않고,
기본적인 프로젝트 설정과 서버/DB EC2 배포, 데이터베이스 설계 등을 진행했습니다.

확인해주시고 피드백 부탁드립니다. 감사합니다!

---

## 작업 현황
- [x] EC2서버에서 MySQL 환경 구축
- [x] EC2서버에 배포 (간단하게 URL 요청을 보냈을 때 응답이 오는 정도만 확인하는 용도)
    - 배포 URL : http://15.165.236.13
- [x] Member 도메인 객체와 저장계층인 MemberRepository 구현
- [x] 세부적인 데이터베이스 설계(진행중)

---

## 고민사항

### 데이터베이스 설계
![tables](https://user-images.githubusercontent.com/15515249/164180288-a5d30ee5-32ce-4a6e-a0c7-a111c3eadb54.jpg)
- DB 입장에선 어떤 정보를 저장해야할 지 많은 고민을 했던 것 같습니다.
- 이번 미션에서는 로직에 있어서 연관관계가 의외로 복잡하게 얽혀있어서 이 부분의 고민이 어려웠습니다.
- 어느 정도 수준까지 구현하는게 맞을까 고민하다가, 일단 최대한 간결하게 주어진 요구사항 수준정도까지만 구현하기로 합의했습니다.

### 객체 설계
- 실제 애플리케이션단에서는 각 도메인 객체별로 어떤 정보를 가지게 해야할 지, 어떤 로직을 가지게 해야할 지를 고민했습니다.
- DB 설계를 진행하면서 조금 더 구체화 해 나갈 예정입니다.

2022-04-20 14:28 UTC, wheejuni requested changes
아직 시작하는 단계라서 리뷰드릴게 많진 않군요.
테이블명은 단수형 명사로 고정 부탁드립니다. 이 부분만 반영하시면 바로 머지 가죠~

2022-04-20 14:28 UTC, wheejuni commented on BE/src/main/java/codesquad/sidedish/domain/address/District.java
> +public enum District {
`District` 가 열거형으로 관리되는게 좋은 설계인지는 잘 모르겠습니다.
지역은 확장되거나 축소될 이슈가 없는 절대적인 존재일까요?

2022-04-20 14:28 UTC, wheejuni commented on BE/src/main/resources/schema.sql
> +create table members (
테이블명엔 단수형 명사를 사용 부탁 드려요.

2022-04-21 01:27 UTC, street62 commented on BE/src/main/resources/schema.sql
> +create table members (
반영했습니다. 감사합니다!

2022-04-21 01:27 UTC, street62 commented on BE/src/main/java/codesquad/sidedish/domain/address/District.java
> +public enum District {
넵 이 부분은 저희 내부적으로 조금 더 고민해 보겠습니다.

2022-04-21 01:28 UTC, merged