[Team-03][BE][루이&쿠킴] - 특정 음식 타입 조회 기능
codesquad-members-2022/sidedish pull request #59
Opened 2022-04-22 02:27 UTC by ku-kim

안녕하세요 `잭`! `루이`와 `쿠킴`입니다    
Spring Data JDBC를 활용해 특정 음식 타입 조회 기능을 구현하여 PR 보냅니다.    
리뷰 감사합니다. 즐거운 주말 되세요 😁  

## 📝Description

Story : 프로트엔드가 특정 음식 타입 조회를 하게 해주세요

API : `GET /api/products?meal={value}`
- meal 타입 value 3가지 (main , soup, side)

`성공` - `200 OK` ,`JSON 리턴`

`실패`(value에 해당하는 데이터가 없는 경우) - `404 Not Found` 

## ✅ Commits

- 테이블 DDL, 더미데이터 생성
- 컨트롤러 / 서비스 / 리포지토리 계층
- 컨트롤러의 DTO 객체 / 서비스의 도메인 객체 / 리포지토리의 Entity 객체로 데이터 구분
- 도메인 객체에서 계산 로직 구현
- 테스트 코드 구현

---

### 결과

<details>
<summary> 테스트 </summary>
<div markdown="1">

![테스트 결과](https://i.imgur.com/wCiLzqw.jpg)

</div>
</details>

2022-04-23 09:38 UTC, guswns1659 requested changes
구현하시느라 수고하셨습니다 👍 
깔끔하게 잘 구현하셨네요! 테스트까지 !! 

몇가지 코멘트와 질문 남겼습니다 ㅎㅎ 확인해주시고 남겨주세요!

2022-04-23 09:38 UTC, guswns1659 commented on BE/src/main/java/sidedish/com/controller/ProductsDtoMapper.java
> +@Component
nit;

개인차가 있겠지만 : ) 
저는 스프링 빈은 스프링 컨테이너 내부에서 라이프사이클을 가져야하는 경우에 빈으로 등록하는 편입니다. 
Utils성 클래스는 빈등록하지 않고 사용하는 편 같아요.

2022-04-23 09:38 UTC, guswns1659 commented on BE/src/main/java/sidedish/com/domain/DiscountPolicy.java
> +	private float discountRate;
nit; 

보통 double이 더 많은 자릿수를 정확하게 표현하기 때문에 double을 사용하는 편입니다. 
다만, 비즈니스 상 float 범위 내 정확도를 표현할 수 있다면 큰 상관은 없습니다.

2022-04-23 09:38 UTC, guswns1659 commented on BE/src/main/java/sidedish/com/repository/ProductsRepository.java
> +@Repository
@Repository는 생략 가능합니다. 혹은 붙일 거라면 여러 Repository 별로 통일성있게 가져가주세요!  :)

2022-04-23 09:38 UTC, guswns1659 commented on BE/src/main/java/sidedish/com/repository/entity/DiscountPolicyEntity.java
> +	@PersistenceConstructor
생성자가 한 개인데 @PersistenceConstructor을 붙인 이유가 있을까요?

2022-04-23 09:38 UTC, guswns1659 commented on BE/src/main/java/sidedish/com/repository/entity/ImageEntity.java
> +	@PersistenceConstructor
ditto

2022-04-23 09:38 UTC, guswns1659 commented on BE/src/main/java/sidedish/com/repository/entity/ProductEntity.java
> +	@PersistenceConstructor
ditto

2022-04-23 09:38 UTC, guswns1659 commented on BE/src/main/java/sidedish/com/service/ProductsService.java
> +		validProducts(products);
nit;

행위로 메서드명을 나타내는 건 어떨까요? 
validateProducts

2022-04-23 09:38 UTC, guswns1659 commented on BE/src/test/java/sidedish/com/acceptancetest/ProductsAcceptanceTest.java
> + * 인수테스트 1 : 프로튼엔드가 특정 음식 타입 조회를 하게 해주세요
테스트 시나리오를 적절하게 작성해주셨네요 👍 

사실 실무에서도 명확하게 분리되고 있지 않지만 인수테스트는 실 사용자에 초점을 맞추고 있습니다. 실제 사용자가 여러분의 사이트에 들어와서 실제 동작하는지 테스트한다는 의미가 강합니다. 

지금 작성하는 테스트는 통합테스트에 가깝지 않나 싶네요 : )

2022-04-23 09:38 UTC, guswns1659 commented on BE/src/test/java/sidedish/com/domain/ProductTest.java
> +	class Describe_constructor {
ask; 

@Nested를 사용하신 이유가 있을까요?!

2022-04-23 09:38 UTC, guswns1659 commented on BE/src/test/java/sidedish/com/repository/ProductsRepositoryTest.java
> +	class Describe_findByMealType {
ditto

2022-04-24 13:54 UTC, merged

2022-04-25 01:37 UTC, ku-kim commented on BE/src/main/java/sidedish/com/controller/ProductsDtoMapper.java
> +@Component
Utils성 클래스는 빈등록없이 사용하는 편이시군요! 말씀 감사합니다. :D

2022-04-25 01:39 UTC, Louie-03 commented on BE/src/main/java/sidedish/com/domain/DiscountPolicy.java
> +	private float discountRate;
`double`이 더 많은 자릿수를 사용할 수 있으니 습관적으로 `double`을 사용해줘도 좋겠네요! 참고하겠습니다 😀

2022-04-25 01:40 UTC, ku-kim commented on BE/src/main/java/sidedish/com/repository/ProductsRepository.java
> +@Repository
통일성을 같도록 하겠습니다. @repository 생략 감사합니다. :D

2022-04-25 01:44 UTC, Louie-03 commented on BE/src/main/java/sidedish/com/repository/entity/DiscountPolicyEntity.java
> +	@PersistenceConstructor
처음에는 생성자가 여러개여서 `@PersistenceConstructor`를 사용해 줬지만 도메인 객체와 엔티티를 분리하는 과정에서 생성자를 하나만 남겨두게 되었습니다.

이후에는 명시적으로 해당 생성자를 사용한다는 것을 나타내기 위해 `@PersistenceConstructor`를 사용했습니다!

2022-04-25 01:45 UTC, Louie-03 commented on BE/src/main/java/sidedish/com/service/ProductsService.java
> +		validProducts(products);
행위를 메서드명으로 나타내도록 수정하겠습니다!

2022-04-25 01:51 UTC, ku-kim commented on BE/src/test/java/sidedish/com/acceptancetest/ProductsAcceptanceTest.java
> + * 인수테스트 1 : 프로튼엔드가 특정 음식 타입 조회를 하게 해주세요
감사합니다. 😁
현재 인수테스트의 범위는 시스템의 모든 로직을 검사하기 보다 API 요청에 대한 응답 결과를 검사하고 있습니다.
말씀처럼 인수테스트와 통합테스트의 명확한 분리에 대한 이해가 어렵네요 :( 

Q)
인수 테스트가 실제 사용자가 사이트에 들어와 실제 동작하는지 테스트 한다면 위 테스트 코드에서 어떤 부분이 추가, 수정되어야 할까요?

2022-04-25 01:53 UTC, ku-kim commented on BE/src/test/java/sidedish/com/domain/ProductTest.java
> +	class Describe_constructor {
[기계인간 이종립님의 JUnit5로 계층 구조의 테스트 코드 작성하기](https://johngrib.github.io/wiki/junit5-nested/) 글을 참고하였습니다.

코드의 행동을 설명하기 위해 Describe - Context - It 패턴을 도입하게 되었고, DCI 패턴 계층을 구분하고 가독성을 높이기 위해 계층 구조로(@nested) 테스트 코드를 작성하였습니다.

2022-04-25 01:54 UTC, ku-kim commented
오늘도 상세한 리뷰 감사합니다. 
주말동안 리뷰 댓글을 남기지 못한 점 죄송합니다. :)

2022-04-25 12:41 UTC, guswns1659 commented on BE/src/test/java/sidedish/com/acceptancetest/ProductsAcceptanceTest.java
> + * 인수테스트 1 : 프로튼엔드가 특정 음식 타입 조회를 하게 해주세요
@ku-kim 
저도 어렵고 공부가 필요한 영역입니다 : ) ㅎㅎ 
주신 질문은 저도 한번 고민해볼게요!

2022-04-25 12:43 UTC, guswns1659 commented on BE/src/test/java/sidedish/com/domain/ProductTest.java
> +	class Describe_constructor {
@ku-kim 
네네 ㅎㅎ 직접 DCI 패턴으로 작성해보니 기존 방식인 GIven-When-Then 방식에 비해서 어떤 장점을 느끼셨나요?

2022-04-25 12:59 UTC, ku-kim commented on BE/src/test/java/sidedish/com/domain/ProductTest.java
> +	class Describe_constructor {
제가 느낀 장점은

1. 테스트 코드의 의미 전달
GIven-When-Then 방식은 테스트코드의 의미를 전달할 때 `void 만약_유요하지않은_product_id가_주어졌을때_음식_상세조회_실패()` 또는 `@DisplayName()`을 사용해 한 줄에 길게 작성되어 한 눈에 보기 어렵지만, DCI 계층은 테스트 결과를 한 눈에 보기 좋다.

2. 유사한 테스트 코드 추가
계층으로 구분되어있다 보니 Describe가 같은 계층은 Context-It만 작성하면 된다.

이 있었습니다. :D 

하지만 단점도 있었는데요.
작성 시간이 타 테스트 코드보다 길었고, 오히려 계층이 복잡해져 IDE에서 스코프 단위로 코드 접기를 하지 않는 이상 더 복잡하게 느껴지기도 했습니다.
작성 시간을 줄이고자 IntelliJ의 Live Templates를 만들었는데 시간이 많이 줄여 사용하고 있습니다. [DCI 패턴 + Live Templates 활용](https://kukim.tistory.com/99)

2022-04-25 13:06 UTC, guswns1659 commented on BE/src/test/java/sidedish/com/domain/ProductTest.java
> +	class Describe_constructor {
@ku-kim 
좋습니다 👍 
어떤 기술이든 장단점이 반드시 있을테고, 본인이 납득할 만한 이유를 가지고 사용하는게 중요하다 생각합니다 : ) 
단점에 대해 Live Templates으로 극복하려는 것도 좋네요 

자바 언어 특성상 class가 중첩되어 나타나고 그에 따른 어노테이션도 많아지면서 가독성이 떨어지는 느낌도 있어서, 팀원들의 합의가 중요해보입니다 : )

2022-04-25 13:18 UTC, ku-kim commented on BE/src/test/java/sidedish/com/domain/ProductTest.java
> +	class Describe_constructor {
납득할 만한 이유를 가지고 사용한다는 점 상기시켜주셔서 감사합니다. 
가장 중요한 것은 팀원들과의 합의! 😁