[Team-31 BE 노리 & 휘] Side-dish 프로젝트 1주차(금요일) 코드 리뷰 요청
codesquad-members-2022/sidedish pull request #60
Opened 2022-04-22 02:49 UTC by nohriter

안녕하세요 31조 휘 노리 입니다 😄

이번 진행상황은 아래와 같습니다!!

## ✏1주차 1차(수요일) 리뷰내용 반영
- 기존 `menu_card` 테이블명 `dish`로 수정
- sub_image가 없는 상황을 고려하여 기존 not null에서 null 이 가능하도록 수정

## 📝 1주차 2차 진행 상황
- 초기 프로젝트 설정 
- API 명세서 작성 (슬라이드 기능으로 인한 카테고리 부분 제외) [API명세](https://documenter.getpostman.com/view/19788070/Uyr8kx1m#a8586776-dcd7-47e4-86b0-bf609199f86d)
- 로컬환경에서 Docker Mysql 연결, `schema.sql`, `data.sql`작성  [DB정리](https://github.com/nohriter/sidedish/wiki/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EC%B4%9D%EC%A0%95%EB%A6%AC)

## ✨ 질문사항
1. 지금까지는 api 별로 각자 기능 개발을 하였는데 JK의 수업에서 하나의 기능을 여러 개의 task로 분리하여 팀원이 task 단위로 개발하는 방식을 추천해줬습니다. 그래서 저희가 이번 프로젝트를 시작할 때 스토리를 만들고 task 단위로 분할하고자 하였는데 어떤 방식으로 나눠야 할지 감이 안와서 결국 이전의 api단위로 나누는 방식으로 진행을 하기로 결정했습니다.  혹시 스토리를 task로 나누는 팁이 있을까요?

2. image가 없는 상황을 고려해서 유동적이게끔 not null -> null 로 수정하였는데 의도하신 부분이 이게 맞는지 궁금합니다.😅

2022-04-23 14:24 UTC, Min-92 requested changes
안녕하세요. 휘, 노리 :)
저번에 리뷰드린 내용 잘 반영해 주셨네요. 추가로 드린부분 확인하시고 고민해보세요 :)

질문주신부분 답변드립니다.
1. JK의 수업을 듣지는 못해서 어떤 의도로 말씀하신지는 모르겠지만 레이어별로 구분해보는것도 하나의 방법이 되지 않을까 싶네요. (a -> 컨트롤러 레이어, b -> 서비스 레이어)
2. 이미지 테이블을 분리하면 음식별로 이미지 개수를 유동적으로 가져갈 수 있을것 같아요.

마지막으로 지금 frontend 디렉토리를 삭제하시면서 충돌이 발생한걸로 보이네요.
충돌 해결하시고 다시 리뷰 요청 부탁드립니다.
@nohriter @hwicode

2022-04-23 14:24 UTC, Min-92 commented on backend/src/main/resources/sql/schema.sql
> +CREATE TABLE IF NOT EXISTS `sidedish`.`category`
테이블명은 단수, 복수 한가지로 통일해서 사용해주세요 :)
https://stackoverflow.com/questions/338156/table-naming-dilemma-singular-vs-plural-names

2022-04-23 14:24 UTC, Min-92 commented on backend/src/main/resources/sql/schema.sql
> +    `id`   INT         NOT NULL AUTO_INCREMENT,
id 타입이 bigint와 int 가 혼재돼있네요.
int와 bitint 범위를 알아봅시다 :)

2022-04-23 14:24 UTC, Min-92 commented on backend/src/main/resources/sql/schema.sql
> +    `delivery_morning` VARCHAR(45) NOT NULL,
새벽배송정보는 가능여부만 필요하지 않을까요?

2022-04-23 14:24 UTC, Min-92 commented on backend/src/main/resources/sql/schema.sql
> +    `sub_image_2`         VARCHAR(150) NULL,
이미지 정보 테이블을 따로 분리하면 이미지 개수를 유동적으로 사용할수 있지 않을까요?

2022-04-24 07:06 UTC, nohriter commented
안녕하세요 왕민 질문에 상세히 답변해주셔서 감사합니다!
코드리뷰 해주신 부분은 같이 의논해보도록 하겠습니다.
충돌발생한 부분 수정하여 재 요청드립니다. 감사합니다 ^^

2022-04-24 07:13 UTC, merged

2022-04-24 07:15 UTC, Min-92 commented
PR 머지했습니다. :)
충돌 원인 파악해보시고, force push는 실제 운영하는 branch인 경우 사용을 지양해야 합니다.
commit revert같은 다른 방식으로 해결하는 방법도 학습해보세요 :)

2022-04-25 02:02 UTC, hwicode commented on backend/src/main/resources/sql/schema.sql
> +    `id`   INT         NOT NULL AUTO_INCREMENT,
`user`와 `dish`는 충분히 많은 값을 가질 수 있다고 생각하여 `bigint`를 사용하였는데 혹시 `id`값으로 `bigint`와 `int`가 혼재되어 있으면 문제가 될까요?(`discount_policy`의 `id`는 `int`로 수정하겠습니다)

2022-04-25 02:12 UTC, Min-92 commented on backend/src/main/resources/sql/schema.sql
> +    `id`   INT         NOT NULL AUTO_INCREMENT,
의도된 부분이군요!
테이블 기본키는 기본적으로 bigint를 사용해서, 오히려 제가 생각하지 못한부분이네요.
카테고리처럼 int 범위를 넘지않을것으로 예상되는 테이블은 int를 사용해도 문제 없을것 같습니다 :)

2022-04-25 03:04 UTC, hwicode commented on backend/src/main/resources/sql/schema.sql
> +CREATE TABLE IF NOT EXISTS `sidedish`.`category`
테이블명을 복수로 통일하겠습니다

2022-04-25 03:05 UTC, hwicode commented on backend/src/main/resources/sql/schema.sql
> +    `sub_image_2`         VARCHAR(150) NULL,
이미지 테이블을 따로 분리하겠습니다!