[team-32][BE][Heyho & 선을로] 1주차 2번째 PR 요청
codesquad-members-2022/sidedish pull request #70
Opened 2022-04-22 03:18 UTC by fpzk5656

안녕하세요? Dan!
Heyho & 선을로 입니다.
1주차 2번째 PR 을 보냅니다.

H2연결 및  더미데이터 데이터테이블에 저장하는 기능을 구현을 하였으며,
더불어 레이어간 DTO 분리와 API구조를 변경 하였습니다.

언제나 좋은 리뷰 감사드립니다!👍

2022-04-22 03:26 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> -		return productService.loadListByType(dishType, sideDishType);
dishType과 sideDishType을 String으로 받고 있습니다.
이것을 Enum클래스로 지정하여 구분할까 하였지만,
데이터 테이블에 저장할 때,어차피 문자열로 저장하기도 하기 때문에
Domain 쪽에서 String으로 가지고 있는 변수를
굳이 DTO쪽에서 Enum으로 가져봤자 큰 의미가 없을 것 같아서 Enum 클래스를 제작하지 않았는데
이 경우에 Enum클래스를 제작할 필요가 있을지 궁금합니다.

2022-04-22 05:33 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> -		return productService.loadListByType(dishType, sideDishType);
### 장점

- enum을 활용하면 입력 string을 제한할 수 있습니다.
- enum으로 로직을 모을 수도 있습니다. 

### 하지만 필요성을 느끼지 못한다면 하지 않는 것을 선택하는 것도 방법입니다.

- enum과 같이 커스텀 객체를 적절히 사용하면 관심사를 분리할 수 있지만, 구조화가 될수록 복잡도는 높아집니다.
- 지금 당장 필요한 만큼만, 너무 먼 미래를 생각하지 않고 개발하는 것도 좋은 방법 입니다. (애자일)

2022-04-22 06:21 UTC, Hyune-c requested changes
수고하셨습니다.

- dto 패키지에 있는 dto들을 레이어별로 분리해주세요. 
네이밍도 일관되지 않아 어느 레이어에서 사용하는 건지 상당히 모호하네요.
- 테스트 코드를 만들어주세요.

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
>  @Controller
`nit`
RestController를 활용하지 않는 이유가 있을까요?

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		List<ProductDTO> dtoList = productService.loadListByType(dishType, sideDishType);
명시적인 구현체 타입이 변수명에 있어야 할까요?

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	public ResponseEntity<CommonResponse<List<SimpleProductInfo>>> loadListByType(
`nit`
Response가 한눈에 보이지 않는군요. 코드 스멜이라고 판단해주시면 좋을 것 같습니다.

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		}
`simpleDtoList` 선언부터 for문까지 하나의 stream으로 처리할 수 있을 것 같습니다.
좀 더 간결한 코드로 개선해보시죠.

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	@GetMapping("/details/{id}")
`nit`
`product -> detail -> id` 보다는 `product -> id -> detail`이 자연스럽지 않을까요?

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		return new CommonResponse(CommonCode.SUCCESS, simpleDtoList).toResponseEntity();
`nit`
`CommonCode.SUCCESS`가 반복되고 있네요. 그렇다면 그냥 `성공` 표준 응답 객체를 만드는 메서드를 별도로 만드는건 어떨까요?

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	public ResponseEntity<CommonResponse<DetailProductInfo>> loadDetails(@PathVariable Integer id) {
api 설계상 반환형은 단수의 detail로 보입니다.
그런데 메서드명은 복수형입니다.

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
>  		productService.ordered(requestProduct);
`nit`
객체지향 이론에 따르면 `객체는 메세지를 통해 협력합니다.`
따라서 수동태보다는 시키는 형태의 네이밍을 추천합니다.

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +	private final Integer quantity;
`nit`
자료형 선언도 `일관적인 코딩 방법`의 하나 입니다.

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +		}
좀 더 좋은 코딩 방법이 있을 것 같습니다.

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
>  	}
`nit`
quantity 하나를 바꾸기 위해 이 많은 필드를 새로 만들어야 할까요. 
불변성을 우선하는 관점에서 나쁜 방법은 아니지만, 다른 방법에 대해서도 고민해보시면 좋을 것 같습니다.

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/resources/sql/schema.sql
> +    imgUrl          VARCHAR(3000)
`nit`
SQL은 관습적으로 `스크리밍 스네이크 케이스`로 작성됩니다.

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +		imgArray = imgUrl.split(",");
imgUrl 샘플을 보니 `,`가 들어가 있지 않은 것 같은데 무슨 의도로 분리하는 건가요?

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/dto/DetailProductInfo.java
> +	}
toString을 임의로 수정하는 건 권장하지 않습니다.

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/repository/MemoryProductRepository.java
>  	}
이 메서드는 무엇을 하는지 잘 이해가 안되네요..?
미완성이라면 TODO를 달아주세요.

2022-04-22 06:21 UTC, Hyune-c commented on be/src/main/resources/application.properties
> +logging.level.kr.codesquad.sidedish=debug
`nit`
yml을 통한 설정도 공부해보시는 것을 추천합니다.

2022-04-24 03:47 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
>  @Controller
그 어노테이션의 존재를 잊고 있었습니다;; 감사합니다

2022-04-24 04:08 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		List<ProductDTO> dtoList = productService.loadListByType(dishType, sideDishType);
정확히 질문이 의도하시는 바를 몰라서 구글링 하다가 Java Naming Convention 번역되있는거 읽어보니까
Collection 타입의 변수 이름은 저장되는 Object의 복수형태로 지으라는 부분이 나오는데
`productDtos` 나 `products` 로 변경 해도 괜찮을까요?

2022-04-24 04:12 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	public ResponseEntity<CommonResponse<List<SimpleProductInfo>>> loadListByType(
제네릭 선언이 많고, 특히 마지막 선언에 `SimpleProductInfo`가 있어서
Response가 한눈에 들어오지 않는 다는 말씀으로 들리는데 맞을까요?

2022-04-24 04:22 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		List<ProductDTO> dtoList = productService.loadListByType(dishType, sideDishType);
아래를 참고해주세요.

https://dev-monkey-dugi.tistory.com/m/94

![image](https://user-images.githubusercontent.com/55722186/164956502-15d1a55f-c290-4d48-8fbc-ed82aad31cf5.png)

2022-04-24 04:22 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	public ResponseEntity<CommonResponse<List<SimpleProductInfo>>> loadListByType(
네 맞습니다.

2022-04-24 04:23 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +		}
`stream`의 `map`기능을 사용하여 간결한 코드로 개선하였습니다.

2022-04-24 04:41 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	public ResponseEntity<CommonResponse<DetailProductInfo>> loadDetails(@PathVariable Integer id) {
아 왜 저렇게 했었나 곰곰이 생각해보니,
URL 명에 details가 들어가서 통일할려는 생각에 `loadDetails`라 지었던 것 같습니다.
말씀을 듣고 다시보니,
URL명의 경우 디테일 정보들 중에 id로 조회하는 느낌이지만,
메소드까지 그럴 필요가 없다는 것을 알았습니다. `loadDetail`로 변경하였습니다.

2022-04-24 04:57 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +		imgArray = imgUrl.split(",");
더미 데이터가 완성되지 않아서 차후 수정 예정이온데
url 이 여러개씩 들어갈 예정 입니다.

2022-04-24 04:59 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/dto/DetailProductInfo.java
> +	}
넵 변경하였습니다!

2022-04-24 05:01 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/repository/MemoryProductRepository.java
>  	}
첨에 이걸로 메모리에 저장하여 제작할 예정이었는데 잊고 있었네요;
필요치 않다 생각하여 삭제 하였습니다.

2022-04-24 05:41 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +		}
사실 어떤 부분을 지적하는 지 정확히 모르겠어서 유심히 살펴본 바
applyEvent에 할인가가 여러개가 들어올 수 있기에,
만약 `이벤트특가`와 `런칭특가`가 동시에 들어왔을 때 30% 할인 받을 것 까지를 염두해서
다음과 같이 private 메소드를 추가하여 코드를 변경하였습니다.
```
public ProductDTO createDTO() {
String[] events = applyEvent.split(",");
int discountPrice = convertDiscountPrice(events, price);

...메소드 반환부분은 생략
}

private int convertDiscountPrice(String[] events, int price) {
		if (events.length == SUPER_SALE_NUM) {
			// 30% 할인
			return (int) (price * SUPER_DISCOUNT);
		}
		if (applyEvent.contains("런칭특가")) {
			// 20% 할인
			return (int) (price * LAUNCHING_DISCOUNT);
		}
		if (applyEvent.contains("이벤트특가")) {
			// 10% 할인
			return (int) (price * EVENT_DISCOUNT);
		}
		return price;
	}
```

2022-04-24 05:45 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
> +	@GetMapping("/details/{id}")
흐름상 `상품 - 자세하게 - 번호` 보다는 `상품 - 번호 - 자세하게` 가 더 낫겠네요.
감사합니다.

2022-04-24 05:50 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
>  		productService.ordered(requestProduct);
`orders`는 3인칭 단수여서 그거 말고 `order`를 쓰면 좀 더 나을까요?

2022-04-24 05:52 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
>  		productService.ordered(requestProduct);
네. 메세지를 전달한다는 개념에서 `order` 가 좀 더 어울릴 것 같습니다.

2022-04-24 05:55 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +	private final Integer quantity;
`quantity`만 Integer를 쓸게 아니라...`price`도 Integer를 적용하는게 좋다는 말씀일까요?

2022-04-24 05:58 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +		}
처음의 코드는 2가지가 불편했습니다.

- if가 반복되고 있다.
- if 조건에 걸리지 않는 `discountPrice` 초기값이 존재한다.

이것을 해결하는 방법으로는 아래와 같은 방법이 있으며, 개인적으로는 enum을 추천합니다.

- swtich-case 문 활용
- 메서드로 분리
- enum 활용

---

30% 할인은 문자열 비교가 아니라 길이 비교를하네요..? 
20%, 10% 할인도 contains로 비교하고 있고.. 
요건이 변경되면 상당히 고치기 어려운 코드가 될 것 같습니다.

2022-04-24 06:01 UTC, Hyune-c commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +	private final Integer quantity;
네. 래퍼형과 프리미티브형의 성능 차이를 떠나, 현대의 개발에서는 협업을 위해 가독성이 더 중요합니다.
일관성 있는 선언도 가독성의 영역입니다.

나중에 다른 개발자가 본다면 왜 굳이 두 필드의 자료형을 다르게 했는지 고민하게 되겠지요.

2022-04-24 06:09 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +	private final Integer quantity;
중요도를 몰라서 몇번이나 질문해야되나 긴가민가하고 놓칠뻔한 주제였는데,
지적해주시고 알려주셔서 감사합니다

2022-04-24 07:16 UTC, merged

2022-04-24 07:34 UTC, fpzk5656 commented on be/src/main/java/kr/codesquad/sidedish/domain/Product.java
> +		}
enum문을 나름 공부해서 적용해보았는데 올바른 방식인지는 모르겠습니다.

시간 관계 상 test코드 까지는 아직 못 하였습니다😢
나머지 내용들도 검토하여 
다음주 PR 때 반영토록 해보겠습니다!
주말 내 시간 내주셔서 감사합니다😍