[BE][Team-26] 1주차 2차 PR
codesquad-members-2022/sidedish pull request #71
Opened 2022-04-22 03:23 UTC by honeySleepr

안녕하세요 디온! Jerry, BC 입니다 👋

1주차 2차 PR 드립니다.

### 한 일

**1. PR 리뷰 반영**
  - [x] 메서드명 수정
  - [x] url menu-> menus
  - [x] @GetMapping 하나로 통일
  - [x] enum int 대신 String으로 넣기
  - [x] @Id 제거
  - [x] MenuResponse로 변경
  - [x] @Repository 제거
  - [x] application.yml 파일 수정
  - [x] schema.sql 수정
  - [x] DB 코멘트 달기
  - [x] menu_order 고치기

<br>

**2. 기능 구현**

- [x] 상세 조회 기능
- [x] 주문 기능  
- [x] 서버 배포 (jerry 서버: http://52.79.50.206:8080/menus/main, BC 서버: http://3.38.230.108:8080/menus/main)
- [x] Swagger GET API 문서 적용

<br>

### 할 일

- [ ] 자동 배포
- [ ] OAuth 로그인
- [ ] 코드 리팩토링
- [ ] Swagger POST 명세 작성
- [ ] 주문 시 재고 수량 검증

2022-04-22 17:10 UTC, ksundong requested changes
안녕하세요!! Jerry, BC 리뷰어 dion입니다.
벌써 두번째 프로젝트도 1주차가 지나갔네요. 시간이 참 빠른 것 같습니다.
개발하느라 고생많으셨습니다.

먼저 드리고 싶은 말씀은, 최소 단위로 기능을 구현하시는 것 부터 차근차근 하시면 좋을 것 같아요. 더 클라이언트에게 중요한 기능은 무엇인지 판단해서, 작업해보시면 좋을 것 같아요.

예를 들어, User를 관리하는 것이 application 에는 없는데, 기능 개발이 완료된건 아니라고 보는게 좋겠죠.

이런 우선순위를 잘 잡는 연습을 해둬야 나중에 취업을 해서도 도움이 될거라고 생각합니다.

## 리뷰 내용 요약

- `Enum`을 적극적으로 활용해보세요.
- 클라이언트가 주문을 처리하게 하는 것 대신 서버가 직접 처리해줍시다.
- 타입을 올바르게 사용해주세요.
- `typeMap` 같은건 필요없을 것 같습니다.
- `@Transactional` 애노테이션에 대해서 공부해보시고 공유해주세요.

고생하셨습니다. 일요일 오후 9시에 최종적으로 머지하겠습니다.
그 전까지 작업해주실 수 있는 부분은 작업해주세요~~~

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/config/SwaggerConfig.java
> +public class SwaggerConfig {
호옹 Swagger를 사용해주셨군요.

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/controller/ApiController.java
> +	}
??? 뭘까요~ 이건 빼주시는게 좋을 것 같네요.

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/controller/MenuController.java
> +	public List<MenuResponse> welcome() {
ㅎㅎㅎ `welcome` 뭔가 괜찮네요.

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/controller/MenuController.java
> +		@ApiParam(name = "type", value = "요청할 메뉴 타입(예: soup)", required = true) @PathVariable("type") String type) {
`type` 은 Enum으로 관리하는 편이 낫지않을까요?

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/controller/MenuController.java
>  	@ResponseBody
아 이거보고 든 생각인데 왜 `RestController` 를 사용해주지 않으셨나요?

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/controller/MenuController.java
> +	@ApiOperation(value = "상세 화면 업데이트", notes = "지정된 id의 메뉴 상세정보를 불러옵니다.")
업데이트가 맞나요?

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/controller/MenuController.java
>  	}
흠 이걸보니 `@Controller` 를 써주신 이유는 알겠는데요.
굳이 써야했나 하는 생각이 드네요. 주문하고 왜 Redirect를 직접 시키시는 걸까요?
우리는 REST API를 만들고 있는데 말이죠..

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/domain/Image.java
> +	private int isMainImage;
왜 `int` 타입인가요?

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/domain/Image.java
> +	private Long id;
여기는 `@Id` 애노테이션이 누락된 이유가 있나요?

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/domain/Menu.java
> +	private String saleType;
왜 `Enum` 사용은 안해주셨나요?

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/domain/Menu.java
>  	private Integer imageId;
이 ImageId는 뭔가요? 요건 OneToOne 매핑이 안되는 구존가요?

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/domain/Menu.java
>  	private int freeShippingMin;
잘 와닿지 않는 네이밍으로 보여요.

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/domain/MenuOrder.java
> +	}
:+1:

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/domain/MenuType.java
> +	));
응? 이런건 어디서 배우셨나요... 그냥 name 받아서 lowercase만 해도 되는걸... 굳이 이렇게 만들어주실 필요는 없을 것 같습니다.

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/dto/DetailMenuImages.java
> +	private int isMainImage;
요건 `boolean` 이 낫겠죠.

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/dto/DetailMenuInfo.java
> +public class DetailMenuInfo {
`Info` 는 없어도 의미전달이 되지 않을까 싶네요.

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/dto/DetailMenuResponse.java
> +	}
잘 만들어주셨어요.

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/dto/OrderRequest.java
> +	private int menuPrice; // 할인 적용된 가격
가격을 `client` 가 결정하나요?

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/dto/OrderRequest.java
> +	}
왜 만들어주셨나요? 의미없는 것 같은데요!

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/repository/ImageRepository.java
> +	List<DetailMenuImages> findInfoByMenuId(@Param("menuId") int menuId);
오호 이런식으로 Projection 해주셨군요.
`Info` 는 빼고 네이밍을 고민해보세요.

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/repository/MenuRepository.java
> +	DetailMenuInfo findDetailMenu(@Param("menuId") int menuId);
응답이 `null` 이 될 수 있는 경우는 없을까요?

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/service/MenuService.java
>  		return null;
아직도 여긴 `null` 을 응답하네요.

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/service/OrderService.java
> +	public MenuOrder save(OrderRequest request) {
`@Transactional` 애노테이션에 대해서 알고 계신가요? 해당 애노테이션을 학습하시고 공유해주세요~~

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/JbcApplication.java
> +@EnableWebMvc
왜 넣어주셨나요?

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/resources/application-local.yml
> +      mode: always
잘 적용해주셨네요~

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/resources/data.sql
> +VALUES ('코드스쿼드', 'Dion');
?!

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/resources/schema.sql
> +CREATE SCHEMA IF NOT EXISTS `sidedish` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
:+1:

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/resources/schema.sql
> +    `image_id`              INT             NOT NULL    COMMENT '대표 이미지 ID',
NOT_NULL CONSTRAINT 를 다 넣는 것은 자칫 잘못하면 DB에 데이터를 못넣는 경우가 있어서 정말 NOT NULL인지 한 번 더 생각해보시길 바랍니다~

2022-04-22 17:10 UTC, ksundong commented on BE/src/main/resources/schema.sql
> +    `menu_price`    INT             NOT NULL        COMMENT '(세일 적용 후) 메뉴 가격',
그럼 세일 전 가격은 어떻게 알 수 있나요?

2022-04-22 17:10 UTC, ksundong commented on BE/README.md
> +!!!! 메뉴 가격은 할인 적용 후의 가격을 보내주셔야 함 !!!!
!!!! 가격은 백엔드가 판단하는게 맞지않을까요 !!!!

2022-04-23 13:56 UTC, jeremy0405 commented on BE/src/main/java/sidedish/jbc/controller/ApiController.java
> +	}
테스트 해본 파일을 실수로 커밋했네요 😅

다음부터 조심하겠습니다!!

2022-04-23 14:20 UTC, jeremy0405 commented on BE/src/main/java/sidedish/jbc/controller/MenuController.java
> +		@ApiParam(name = "type", value = "요청할 메뉴 타입(예: soup)", required = true) @PathVariable("type") String type) {
`@PathVariabel` 로 Enum을 바로 받아 올 수 있는 것을 몰랐습니다.

type이 Enum의 형식과 동일하면 바로 매칭이 되는 것을 확인하였고 Converter를 통해 소문자 url path을 Enum 형식으로 바로 받도록 리팩토링을 진행했습니다.

2022-04-23 14:21 UTC, honeySleepr commented on BE/src/main/java/sidedish/jbc/controller/MenuController.java
> +	@ApiOperation(value = "상세 화면 업데이트", notes = "지정된 id의 메뉴 상세정보를 불러옵니다.")
의미가 정확히 전달되도록 '상세 요청'으로 바꿨습니다!

2022-04-23 14:27 UTC, jeremy0405 commented on BE/src/main/java/sidedish/jbc/controller/MenuController.java
>  	}
제가 REST API에 대해 이해를 못하고 있었던 것 같습니다.

Redirect 코드 대신 클라이언트에 POST에 대한 결과에 대한 정보를 JSON 형식으로 내리도록 클라리언트 분들과 협의 해보겠습니다.

2022-04-23 14:31 UTC, jeremy0405 commented on BE/src/main/java/sidedish/jbc/domain/Image.java
> +	private int isMainImage;
`boolean` 으로 변경하였습니다.

2022-04-23 14:31 UTC, jeremy0405 commented on BE/src/main/java/sidedish/jbc/domain/Image.java
> +	private Long id;
실수로 빼먹은 것 같습니다. 추가했습니다 :)

2022-04-23 14:37 UTC, jeremy0405 commented on BE/src/main/java/sidedish/jbc/domain/Menu.java
> +	private String saleType;
Enum으로 변경하였습니다!!

2022-04-23 14:49 UTC, jeremy0405 commented on BE/src/main/java/sidedish/jbc/domain/Menu.java
>  	private Integer imageId;
ImageId 대신 ImagePath로 변경이 가능할 것 같아서 변경했습니다!

감사합니다!

2022-04-23 14:53 UTC, honeySleepr commented on BE/src/main/java/sidedish/jbc/domain/Menu.java
>  	private int freeShippingMin;
조금 더 명확하게 `freeShippingStartingPrice`로 변경하겠습니다~

2022-04-23 14:58 UTC, jeremy0405 commented on BE/src/main/java/sidedish/jbc/dto/OrderRequest.java
> +	private int menuPrice; // 할인 적용된 가격
저희가 결정하도록 변경해보겠습니다.

2022-04-23 14:59 UTC, jeremy0405 commented on BE/src/main/resources/schema.sql
> +    `menu_price`    INT             NOT NULL        COMMENT '(세일 적용 후) 메뉴 가격',
저희가 세일을 처리하도록 변경해보겠습니다!!

2022-04-23 15:02 UTC, honeySleepr commented on BE/src/main/java/sidedish/jbc/dto/OrderRequest.java
> +	private int menuPrice; // 할인 적용된 가격
빽에서 처..처리하겠습니다!😅

2022-04-23 16:38 UTC, honeySleepr commented on BE/src/main/resources/schema.sql
> +    `image_id`              INT             NOT NULL    COMMENT '대표 이미지 ID',
넵 고민해보겠습니다

2022-04-23 16:38 UTC, honeySleepr commented on BE/src/main/java/sidedish/jbc/service/MenuService.java
>  		return null;
AOS 요구사항에 메인 화면을 띄울 때 모든 메뉴타입을 한번에 요청하지 않고 메뉴 타입별로 각각 구분해서 호출하라는 조건이 있어서 해당 메서드는 사용하지 않게 될 것 같습니다. 삭제하도록 하겠습니다!

2022-04-23 16:38 UTC, honeySleepr commented on BE/src/main/java/sidedish/jbc/repository/MenuRepository.java
> +	DetailMenuInfo findDetailMenu(@Param("menuId") int menuId);
menuId를 통해 요청할 때 null이 나올 수 있겠군요. 이 부분은 고민을 더 해보겠습니다

2022-04-23 16:38 UTC, honeySleepr commented on BE/src/main/java/sidedish/jbc/repository/ImageRepository.java
> +	List<DetailMenuImages> findInfoByMenuId(@Param("menuId") int menuId);
넵!

2022-04-23 16:38 UTC, honeySleepr commented on BE/src/main/java/sidedish/jbc/dto/OrderRequest.java
> +	}
앗 그러네요! 지적 감사합니다~~ :)

2022-04-23 16:38 UTC, honeySleepr commented on BE/src/main/java/sidedish/jbc/domain/MenuType.java
> +	));
넵 적용해보겠습니다!

2022-04-23 16:38 UTC, honeySleepr commented on BE/src/main/java/sidedish/jbc/JbcApplication.java
> +@EnableWebMvc
Swagger를 사용하기 위해 등록해주었는데, Main 실행 파일 대신 SwaggerConfig 파일로 옮겨주는게 맞는 것 같습니다. 
@EnableWebMvc의 역할에 대해 조금 찾아보았는데 'Spring에서 사용되는 Config 값들을 자동으로 세팅해준다!'라고 대략적으로 밖에 이해를 못했네요.. 더 공부해보겠습니다!

2022-04-23 17:28 UTC, jeremy0405 commented on BE/src/main/java/sidedish/jbc/service/OrderService.java
> +	public MenuOrder save(OrderRequest request) {
`@Transactional`은 메소드, 클래스, 인터페이스에 사용이 가능하고 아래와 같은 옵션을 가지고 있습니다.
- isolation
- propagation
- noRollbackFor
   - 특정 예외 발생 시 Rollback 처리를 하지 않도록 함
- rollbackFor
   - 특정 예외 발생 시 Rollback 처리를 함 
   - Defalut: Unchecked Exception을 Rollback 함
- timeout
   - 지정한 시간 내에 메소드 수행이 완료되지 않는다면 Rollback
- readOnly
   - true로 설정 시 insert, update, delete sql문이 실행된다면 예외가 발생
   - (insert 작업 시 auto_increment 옵션 적용 된 id 값은 롤백되지 않음)

<br>

Transaction annotation은 위와 같은 옵션으로 트랜잭션 특성 4가지(원자성, 일관성, 격리성, 영속성)를 지원합니다.

2022-04-24 11:40 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/controller/MenuController.java
>  	}
결과를 내려줄지 아니면 그냥 성공되었음을 알려만 줄지도 논의해보시면 좋을 것 같습니다.

2022-04-24 11:43 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/service/OrderService.java
> +	public MenuOrder save(OrderRequest request) {
네 이부분은 잘 알고 있어야 하는 부분이어서 한 번 언질을 드렸습니다~

2022-04-24 11:43 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/JbcApplication.java
> +@EnableWebMvc
넵 더 공부해보시면 좋을 것 같네요.

2022-04-24 11:50 UTC, ksundong approved these changes
고생하셨습니다~ 추가적으로 리뷰 드린 내용도 참고하셔서 다음주도 파이팅해서 진행해주세요!

2022-04-24 11:50 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/config/WebConfig.java
> +}
컨버터가 필요할까요? 컨버터 없이 진행해보시길 바랍니다.
그리고 `Component` 로 만들어 주셨다면, 직접 생성하는 것보다는 주입을 받아서 처리하시는게 맞을 것 같아요.

2022-04-24 11:50 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/domain/Menu.java
> +			", freeShippingMin=" + freeShippingStartingPrice +
여기 `freeShippingMin` 이 남아있네요.

2022-04-24 11:50 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/domain/convertor/MenuTypeConvertor.java
> +}
굳이 필요는 없어보여요 ㅎㅎ

2022-04-24 11:50 UTC, merged

2022-04-24 11:50 UTC, honeySleepr commented on BE/src/main/java/sidedish/jbc/service/OrderService.java
> +	public MenuOrder save(OrderRequest request) {
`@Transactional`은 메소드나 클래스에서 발생하는 트랜잭션에 대해서 자동적으로 Commit과 Rollback을 처리 해주도록 설정하는 어노테이션 입니다.
'DB에 대한 동시성 이슈를 해결해주는 어노테이션' 정도로 이해하였습니다. 

한 트랜잭션에 대해 어떻게 격리 처리를 해줄지를 결정하는 `isolation` 옵션, 
한 트랜잭션 내에서 다른 트랜잭션을 호출 할 경우 어떻게 처리할지를 결정하는 `propagation` 옵션, 그리고 위에서 제리가 언급해준 옵션들을 지정해 줄 수 있습니다.

(propagation은 아직 이해가 잘 안되어서 더 공부해보겠습니다!)

2022-04-24 12:03 UTC, ksundong commented on BE/src/main/java/sidedish/jbc/service/OrderService.java
> +	public MenuOrder save(OrderRequest request) {
'DB에 대한 동시성 이슈'를 해결하기 위한 애노테이션은 뭔가 핵심과는 거리가 있는 것 같기도하고 아리까리 하네요.
트랜잭션이 동시성 제어를 의미하는 것은 맞지만, `@Transactional` 은 트랜잭션을 개발자가 쉽게 다룰 수 있도록 지원하는 애노테이션이 더 가까운 설명이 아닌가하는 생각이 듭니다.

Transaction isolation 은 호눅스가 잘 설명해주실거에요. 잘 공부해두셨다가 써먹으시면 될 것 같습니다.
propagation 은 어떤 옵션이 있는지, 잘 공부해두시고 써먹으시면 좋습니다.

2022-04-25 03:43 UTC, jeremy0405 commented on BE/src/main/java/sidedish/jbc/domain/Menu.java
> +			", freeShippingMin=" + freeShippingStartingPrice +
꼼꼼하게 확인 못한 것 같네요 수정하겠습니다!