[team-04][BE] sidedish 1주차 두번째 PR #2
codesquad-members-2022/sidedish pull request #74
Opened 2022-04-22 03:26 UTC by CMSSKKK

안녕하세요! Jack🙇‍♂️

짱민&로니입니다.

1주차 두번째 PR을 보냅니다.
잘 부탁드립니다!

## 진행 사항
### ERD
- User와 Order에 해당하는 테이블은 아직 추가하지 않았습니다.
<img width="273" alt="erd" src="https://user-images.githubusercontent.com/81129309/164589090-077706da-0e3d-4b8d-8088-eec6784c101f.PNG">

### 기능 구현
- category별 dish를 가져오는 API 
   - [mockAPI](https://b1fc7859-683f-4397-8fca-70ce96ce65f6.mock.pstmn.io/1)
- category별 dish 페이징 API
   - [mockAPI]
- Event별 dish를 가져오는 API
   - [MockAPI](https://b1fc7859-683f-4397-8fca-70ce96ce65f6.mock.pstmn.io/special)
- dish 하나의 디테일 정보를 가져오는 API
  - [MockAPI](https://b1fc7859-683f-4397-8fca-70ce96ce65f6.mock.pstmn.io/special)

> 테스트 코드의 경우 dataJdbc 작동을 확인하기위한 코드입니다. 다음 PR에는 의미있는 테스트코드를 작성하도록 하겠습니다.

### 배포
- EC2 서버에 mysql를 함께 설치하여 배포테스트 진행했습니다.
- NginX에 reactapp 실행 테스트 진행

2022-04-23 08:45 UTC, guswns1659 requested changes
구현하느라 수고하셨습니다. 👍
지난번에 남긴 리뷰도 잘 반영됐네요 
몇가지 리뷰 남겼고 반영 후 한번 더 요청 주세요 : )

nit;
코드 내 불필요한 공백이 많이 있습니다. 코드 포맷팅 한번 진행해주세요 !

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/java/kr/codesquad/sidedish/controller/CategoryController.java
> +    public ResponseEntity<CategorizedDishes> findCategorizedById(@PathVariable Long id) {
nit; 

findXXByXX 와 같은 메서드 네이밍 컨벤션은 주로 Repository에서 사용합니다. 
현재 로직 상 CategoryController와 Service가 비즈니스 로직이 없고 DB 조회 역할만 있는 것 같아서 큰 상관은 없을텐데, 

추후 로직이 생긴다면 어떤 기능을 하는지 표현할 수 있는 네이밍이 좋을 것 같습니다

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/java/kr/codesquad/sidedish/controller/CategoryController.java
> +    @GetMapping("/{id}")
아래 DishController는 prefix로 dish가 포함되는데 category도 넣으면 어떨까요? 
id의 대상을 api 내 표현하면 더 명확합니다 : )
```
GET dishes/{id} -> dish를 조회하는구나 
GET /{id} -> 무엇을 조회하지? 
```

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/java/kr/codesquad/sidedish/controller/DishController.java
> +@RequestMapping("/dish")
REAT API 에서는 주로 단수보단 복수형을 사용합니다. 
```
GET /dishes/1 -> dishes 중에 id=1인 dish를 조회한다. 
```

dishes가 어떨까요?!

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/java/kr/codesquad/sidedish/controller/DishController.java
> +    @GetMapping("/paging")
REST API 설계할 때는 URI로는 자원의 위치, 정보를 나타내고, HTTP method로 자원에 대한 행위를 표현합니다. 
그래서 URI 내부에는 동사 대신 명사를 사용합니다. 동사로 표현되는 행위를 HTTP 메서드로 이미 표현하고 있기 때문이죠. : )
[참고 블로그](https://meetup.toast.com/posts/92)

paging이라는 의미를 명사로 사용하셨을 수도 있는데, 그렇다해도 paging이라는 의미를 굳이 표현할 필요는 없어보여요. 아래와 같이 표현해도 dishes를 조회한다는 의미는 전달되는 것 같습니다 :) 

```
GET /dishes?lastDishId=3?categoryId=4
```

추가로 
- lastDishId처럼 이전 page의 마지막 번호를 offset이라는 단어를 사용하곤해서 offset도 추천드려요! 
- Category가 dish보다 더 상위 계층으로 보여서 categoryId가 먼저 오는 건 어떨까요? 

최종적으로는 아래와 같은 형식일텐데, 이건 저의 제안이고 ㅎㅎ 납득되신다면 이렇게 사용해주세요. 아니어도 괜찮습니다. 

```
GET /dishes?categoryId=4?offset=3
```

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/java/kr/codesquad/sidedish/repository/JdbcDishRepository.java
> +    @Query("select * from dish where category_id = :categoryId and id > :lastDishId limit 4")
nit;
아래처럼 limit에 offset을 줄 수 있습니다. 그런데 사용되지 않는 메서드로 보이네요? 사용하지 않는 메서드면 삭제해주세요 ~ 

```
select * from dish where category_id = :categoryId limit :lastDishId 4
```

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/java/kr/codesquad/sidedish/repository/JdbcDishRepository.java
> +    public List<Dish> findDishesByCategoryId(Long categoryId, PageRequest pageRequest);
인터페이스 내에서는 public 메서드가 암묵적으로 적용되어 있습니다. public 삭제해주세요 : )

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/java/kr/codesquad/sidedish/service/DishService.java
> +    public List<DishSimpleResponse> getNextDishes(Long lastDishId, Long categoryId) {
페이징 잘 구현하셨습니다 👍

추후에 도움될 수 있는 피드백 남기자면 pagination api 구현할 때는 보통 아래와 같이 api를 설계합니다. 
GET /XXX?page=0?size=4 

이런 방식의 장점은 현재 페이지가 얼마인지 서버에서 알 필요없이 클라이언트에서 정해서 준다는 점이고, 
추후 Page 사이즈가 변경해도 서버에서는 수정할 것이 없습니다.

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/java/kr/codesquad/sidedish/controller/EventController.java
> +    @GetMapping("/special")
ditto 

REST API 설계 관련

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/java/kr/codesquad/sidedish/domain/Dish.java
> +    @MappedCollection(idColumn = "DISH_ID", keyColumn = "ID")
👍

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/java/kr/codesquad/sidedish/repository/JdbcDishRepository.java
> +    public boolean delete(Long id);
👍

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/java/kr/codesquad/sidedish/service/CategoryService.java
> +        Category category = jdbcCategoryRepository.findById(categoryId).orElseThrow();
nit; 

어떤 exception인지 클라이언트에게 알려줄 수 있는 Custom exception을 사용하면 어떨까요?

2022-04-23 08:45 UTC, guswns1659 commented on BE/src/main/resources/data.sql
> +insert into event (name, description) values ('짱민반찬추천2', '이건 못참취');
ㅋㅋㅋㅋ 👍

2022-04-24 13:54 UTC, merged

2022-04-25 02:02 UTC, CMSSKKK commented on BE/src/main/java/kr/codesquad/sidedish/controller/CategoryController.java
> +    public ResponseEntity<CategorizedDishes> findCategorizedById(@PathVariable Long id) {
기능 구현에 신경을 쏟느라 메서드 네이밍에 대해서 크게 고민하지 못한 것 같습니다! 

고민해보도록 하겠습니다!

2022-04-25 02:05 UTC, CMSSKKK commented on BE/src/main/java/kr/codesquad/sidedish/controller/CategoryController.java
> +    @GetMapping("/{id}")
main 기능의 api라고 생각해서 생략했었는데, api사용자가 의미를 알기 어려운 것 같습니다. 

말씀대로 추가해서 의미를 명확하게 하겠습니다 ㅎㅎ

2022-04-25 02:08 UTC, CMSSKKK commented on BE/src/main/java/kr/codesquad/sidedish/controller/DishController.java
> +@RequestMapping("/dish")
단수 혹은 복수로 통일하는 것으로만 알고있었는데, 주로 복수형을 사용하는군요 ㅎㅎ

참고해서 작성하겠습니다!

2022-04-25 02:12 UTC, CMSSKKK commented on BE/src/main/java/kr/codesquad/sidedish/repository/JdbcDishRepository.java
> +    @Query("select * from dish where category_id = :categoryId and id > :lastDishId limit 4")
`PageRequest` 사용법을 익히기 전에 구현해봤던 메서드인데 삭제하겠습니다! 

아직 sql과 관련해서 공부가 부족한데 예시까지 작성해주셔서 감사합니다!

2022-04-25 02:14 UTC, CMSSKKK commented on BE/src/main/java/kr/codesquad/sidedish/service/CategoryService.java
> +        Category category = jdbcCategoryRepository.findById(categoryId).orElseThrow();
넵! 다음 PR에는 예외처리까지 신경써서 구현하겠습니다

2022-04-25 02:27 UTC, CMSSKKK commented on BE/src/main/java/kr/codesquad/sidedish/controller/DishController.java
> +    @GetMapping("/paging")
기능을 구현해보기 위한 임의의 API 네이밍이었는데 친절하게 예시 및 설명해주셔서 너무 감사합니다 ㅠㅠ 

참고 블로그와 예시 참고해서 수정해보도록 하겠습니다!!

2022-04-25 02:30 UTC, CMSSKKK commented on BE/src/main/java/kr/codesquad/sidedish/service/DishService.java
> +    public List<DishSimpleResponse> getNextDishes(Long lastDishId, Long categoryId) {
Paging과 관련해서 예시를 통해서 참고할 피드백을 너무 자세히 남겨주셔서 감사합니다! 

다음 PR에 반영해서 제출하도록 하겠습니다!

2022-04-25 07:33 UTC, leezzangmin commented on BE/src/main/resources/data.sql
> +insert into event (name, description) values ('짱민반찬추천2', '이건 못참취');
ㅎㅎㅎㅎ 감사합니다....!

2022-04-26 10:22 UTC, guswns1659 commented
@CMSSKKK @leezzangmin 두분 다 수고 하셨습니다 : )