[Team-35 BE] 기획전, 일반 진열 상품 카테고리별 상품 목록 조회 기능 구현
codesquad-members-2022/sidedish pull request #84
Opened 2022-04-22 04:16 UTC by naneun

안녕하세요 Team-35 에서 백엔드를 담당한 테리와 리아코입니다. 🙆‍♀️🙆‍♂️
기획전, 일반 진열 상품 카테고리별 상품 목록 조회 기능 구현을 완료하여 PR 요청드립니다 😄

# API 명세
  - http://54.180.92.20:8080/swagger-ui/index.html

# API 결과
  - http://54.180.92.20:8080/api/exhibitions/1
  - http://54.180.92.20:8080/api/exhibitions/2

# 개념적 설계 ERD
![SmartSelectImage_2022-04-21-13-08-28](https://user-images.githubusercontent.com/47964708/164370351-1be1c8aa-ad11-4b5c-b2f5-0d3146ab20c2.png)  

# 개념 스키마
![SmartSelectImage_2022-04-22-04-42-14](https://user-images.githubusercontent.com/47964708/164540308-db6565be-6913-46c4-97d7-1c72682d9862.png)  

# 한 일
  - [x] 기획전, 일반 진열 상품 카테고리별 상품 목록 조회 기능 구현

# 해야할 일
  - [ ] CORS 에러 관련 문제 해결

감사합니다! .🤗

2022-04-23 12:33 UTC, tmdgusya requested changes
코드가 짧고 간결한 부분이 많네요 ㅎㅎ 좋습니다.

몇가지만 수정하고 넘어가시죠

2022-04-23 12:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/api/ExhibitionController.java
> +            @PathVariable @Validated @Positive @Min(1) long exhibitionId) {
Validation 이 안되는거 같아요 
어떻게 해야 Validation 이 정상적으로 작동할지 공부해보세요. 그리고 어떤식으로 에러처리를 해야할지도요~!

<img width="845" alt="image" src="https://user-images.githubusercontent.com/57784077/164893881-391b587f-35f7-4d2e-b0c5-62fd236a1a7c.png">

2022-04-23 12:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/Exhibition.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
혹시 왜 기본생성자가 필요한지에 대해서 아시나요?
모르시면 **JavaBeans Convention** 을 공부해보셔도 좋습니다.

2022-04-23 12:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/Exhibition.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
Protected Level 좋네요 ㅎㅎ

2022-04-23 12:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/domain/entity/reference/Category.java
> +    private Set<CategoryHasSideDish> categoryHasSideDishes;
혹시 클래스로 따로 분리하신 이유는 무엇일까요?

음 뭔가 ID 만 있는거 같아서 분리가 필요한가? 라는 생각이 들어서요.

2022-04-23 12:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/domain/entity/reference/SideDishImage.java
> +@AllArgsConstructor
저는 개인적으로 Lombok 을 써도 된다고 주장하는 파이긴 한데, 롬복의 위험성은 아셨으면 좋겠네요

https://kwonnam.pe.kr/wiki/java/lombok/pitfall

2022-04-23 12:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/dto/response/SideDishCardResponse.java
> +public class SideDishCardResponse {
Swagger 를 사용하시면 @ApiModel 이란것도 이용해보시죠~ @ApiProperty 와

2022-04-23 12:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/interceptor/CorsInterceptor.java
> +        response.setHeader("Access-Control-Allow-Headers", "x-requested-with, origin, content-type, accept");
Response 에 이 값을 넣어주는 이유는 무엇일까요?

2022-04-23 12:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/service/ExhibitionService.java
> +            }
함수로 분리하는건 어떨까요 ㅎㅎ?

2022-04-23 12:33 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/error/ErrorCode.java
> +    EXHIBITION_VALIDATION_ERROR("E001", HttpStatus.INTERNAL_SERVER_ERROR, "기획전 아이디가 유효하지 않습니다.");
저도 예전에는 code 를 썼었는데 요즘들어서는 사실 이런 생각도 해요. 

HTTP STATUS CODE 로는 불가능 한걸까? HTTP STATUS CODE 로 대체 가능하다면 그렇게 해주시는게 좋을거 같아요 ㅎㅎ

2022-04-24 05:52 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/dto/response/SideDishCardResponse.java
> +public class SideDishCardResponse {
아직은 어설프고 수정이 잦아서 부수적인 기능들은 작성하지 않고 있었습니다 ㅎㅎ! 그래도 리뷰주신 덕분에 해당 어노테이션들을 사용하여 Swagger 문서를 조금 더 이해하기 쉽게 만들어보았습니다! 감사합니다~! 🤩

2022-04-24 05:55 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/service/ExhibitionService.java
> +            }
이 부분은

https://github.com/codesquad-members-2022/sidedish/pull/84#discussion_r856886777

여기서 리뷰주신 내용과 관련이 있어서 비대하더라도 날 것 그대로 두고 있었습니다 😭
다대다 관계를 끌어오는 로직들이 있어서 어떻게 더 좋은 방법이 없을까 고민하고 있습니다!

리뷰 주셔서 일단 먼저 단순하게 메서드 길이를 줄이는 목적으로 분리를 해보았습니다! 감사합니다~! 😄

2022-04-24 05:57 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/error/ErrorCode.java
> +    EXHIBITION_VALIDATION_ERROR("E001", HttpStatus.INTERNAL_SERVER_ERROR, "기획전 아이디가 유효하지 않습니다.");
현재 어플리케이션 단에서나 클라이언트 단에서 code 값을 처리하는 로직이 없어서 뺄까 생각 중이었는데 말씀주신 덕분에 바로 제외시켰습니다! ㅎㅎ ☺ HTTP STATUS CODE 부분은 아직까지도 알쏭달쏭해서 대체가 가능하도록 학습해보고 분류해보도록 하겠습니다! ㅎㅎ 감사합니다~! 로치 🤩

2022-04-24 06:01 UTC, naneun commented
안녕하세요 로치 리뷰어님! ㅎㅎ Validation 기능도 확인해주시고 감사드립니다 ㅎㅎ pr 마감 시간을 맞추느라 미처 처리하지 못하고 제출했는데 꼼꼼히 봐주시는 로치 덕분에 잊지 않고 문제를 해결할 수 있었습니다! 현재 단계에서 해결할 수 있는 부분들은 간단하게 반영해놓았습니다! 리뷰주신 내용 중 학습해야할 부분들은 조금 더 생각을 정리하여 코멘트 달도록 하겠습니다~! 개인미션 때부터 좋은 리뷰를 남겨주셔서 진심으로 감사드립니다~!! 🤗

2022-04-24 16:33 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/domain/entity/reference/SideDishImage.java
> +@AllArgsConstructor
@AllArgsConstructor 어노테이션의 경우 선언한 필드를 순서대로 파라미터로 설정할 것 같아 항상 필드 순서를 변경하면 해당 생성자를 호출하는 부분도 맞춰서 수정했었습니다! 게다가 생성자 대신에 정적 팩토리 메서드를 사용해서인지 생성자 인자의 순서를 직접 확인할 수 있어서 현재까지는 이러한 위험성이 존재하는 지 몰랐었습니다! ㅎㅎ 보내주신 링크에서 해당 어노테이션의 위험성과 직접 만든 생성자에 @Builder 어노테이션을 붙여 필드 순서가 아닌 이름으로 값을 설정하는 방식도 존재한다는 것을 알게되었습니다! 저에게는 두 방식 중 @AllArgsConstructor 을 사용하고 한 번 더 필드들을 확인하면서 구조 파악도 할겸 코드를 읽는 방식이 더 좋을 것 같습니다! 😄 그 외에도 몰랐던 내용들이 많아서 Lombok 을 사용할 때 항상 유의하면서 작성하도록 하겠습니다! 감사합니다 로치~! 🤩

2022-04-24 17:06 UTC, naneun commented on backend/src/main/java/com/terria/sidedish/api/ExhibitionController.java
> +            @PathVariable @Validated @Positive @Min(1) long exhibitionId) {
1. @Validated 어노테이션을 Class 레벨에서 선언하고  @Positive 어노테이션에 message 속성 값을 설정해주었습니다.
2. @ExceptionHandler 어노테이션을 사용하여 ConstraintViolationException 예외를 처리할 메서드를 정의하였습니다.
3. 해당 메서드는 반환 값이 ErrorResponse 였는데 해당 클래스의 getter 프로퍼티를 정의해놓지 않아서 클라이언트에 응답시 문제가 발생하였습니다. 따라서, @Getter 어노테이션을 사용하여 해결했습니다.

3. 의 경우 아래 리뷰주신 내용인 기본 생성자가 필요한 이유 및 JavaBeans Convention 과 관련이 있어보여 같이 학습하여 정리해보도록 하겠습니다~ 리뷰 감사드립니다! 로치~🤗

2022-04-25 02:53 UTC, mybloom commented on backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/Exhibition.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
프레임워크에서 Bean으로 사용하기 위해 자바빈 컨벤션을 지켜 객체를 생성하는데 문제가 없도록 하는 것으로 알고 있습니다. 

Exhibition은 Spring Data JDBC에서 사용하는 엔티티로 
Spring Data JDBC에서 객체 생성은 아래 3가지 조건 중 한가지를 사용합니다 .
1. 단일 생성자가 있는 경우 사용
2. 생성자 여러 개 있는 경우 @PersistenceConstructor 애노테이션이 있는 생성자 사용
3. 기본 생성자가 있는 경우, 다른 생성자는 무시되고 기본 생성자 사용

그러므로 단일 생성자로 모든 인자를 가진 생성자를 사용해도 되지만, 나중에 다른 생성자가 생겼을 경우 객체 생성에 에러가 발생할 수 있으므로 확실하게 기본 생성자를 작성해두어 Spring Data JDBC에서 객체 생성에 문제가 없도록 하기 위해 기본 생성자를 명시적으로 선언해주었습니다.

2022-04-25 03:00 UTC, mybloom commented on backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/Exhibition.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
그리고 생성자의 레벨을 Protected level로 설정해준 부분은 확실하지가 않은 부분이긴 한데요.

Spring Data JDBC에서 엔티티의 객체를 생성할 때 런타임시 내부적으로 팩토리 클래스를 만들어 생성자를 바로 호출한다고 되어 있었습니다. 
팩토리 클래스가 어디에 생겨서 어떻게 동작하는지 확실하지가 않은데요. 만약 Exhibition 클래스 내부에 생성한다면 private 레벨로 설정해도 되지 않나라고 생각합니다.

2022-04-25 03:12 UTC, mybloom commented
안녕하세요 로치,
테리입니다.

여러 가지 주제로 상세하게 리뷰 남겨주셔서 공부할 수 있는 기회를 주셔서 감사합니다. 
생성자와 롬복은 혼자 공부해보면서 에러가 생겼을 때 해결하지 못하는 상황이 발생하여 급하게 공부했었는데요. 
이번 기회에 조금 더 확실하게 공부해보았습니다. 그러나 여전히 이렇게 답변을 작성한 것이 리뷰어의 의도에 맞는 답일까 란 의문도 들기도 합니다.

스웨거나 Validation은 정확히 공부해보지 못했는데요. 다름 PR까지 더 정리해보도록 하겠습니다. 
감사합니다

2022-04-25 03:14 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/service/ExhibitionService.java
> +            }
네넵~! 좋습니다

2022-04-25 03:15 UTC, tmdgusya commented on backend/src/main/java/com/terria/sidedish/domain/entity/reference/SideDishImage.java
> +@AllArgsConstructor
네넵 좋아요 롬복자체에 문제가 있는건 아니지만 롬복으로 문제가 생길수도 있어서 알아두시면 좋습니다

2022-04-25 03:16 UTC, merged

2022-04-25 03:16 UTC, tmdgusya commented
고생하셨습니다 :)